barcodes/urls.py
from django.conf.urls import url
from . import views

app_name = "barcodes"

urlpatterns = [
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/barcodeset/$",
        view=views.BarcodeSetListView.as_view(),
        name="barcodeset-list",
    ),
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/barcodeset/create$",
        view=views.BarcodeSetCreateView.as_view(),
        name="barcodeset-create",
    ),
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/barcodeset/(?P<barcodeset>[0-9a-f-]+)/$",
        view=views.BarcodeSetDetailView.as_view(),
        name="barcodeset-detail",
    ),
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/barcodeset/(?P<barcodeset>[0-9a-f-]+)/update$",
        view=views.BarcodeSetUpdateView.as_view(),
        name="barcodeset-update",
    ),
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/barcodeset/(?P<barcodeset>[0-9a-f-]+)/delete$",
        view=views.BarcodeSetDeleteView.as_view(),
        name="barcodeset-delete",
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.shortcuts import render
from django.views import defaults as default_views
from django.views.generic import TemplateView

from projectroles.views import HomeView
from sentry_sdk import last_event_id


def handler500(request, *args, **argv):
    return render(request, "500.html", {"sentry_event_id": last_event_id()}, status=500)


urlpatterns = [
    url(r"^$", HomeView.as_view(), name="home"),
    url(r"^about/$", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),
    # Login and logout
    url(r"^login/$", auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    url(r"^logout/$", auth_views.logout_then_login, name="logout"),
    # Auth
    url(r"api/auth/", include("knox.urls")),
    # Iconify SVG icons
    url(r"icons/", include("dj_iconify.urls")),
    ## SODAR Core
    # Projectroles URLs
    url(r"^project/", include("projectroles.urls")),
    # Filesfolders URLs
    url(r"^filesfolders/", include("filesfolders.urls")),
    # django-db-file-storage URLs (needed for admin, obfuscated for users)
    url(r"^xu7in5zs9lylar0n/", include("db_file_storage.urls")),
    # Timeline URLs
    url(r"^timeline/", include("timeline.urls")),
    # User Profile URLs
    url(r"^user/", include("userprofile.urls")),
    # Admin Alerts URLs
    url(r"^alerts/", include("adminalerts.urls")),
    # Background jobs URLs
    url(r"^bgjobs/", include("bgjobs.urls")),
    # Site Info URLs
    url(r"^siteinfo/", include("siteinfo.urls")),
    # API Tokens URLs
    url(r"^tokens/", include("tokens.urls")),
    ## Local Apps
    url(r"^sequencers/", include("sequencers.urls")),
    url(r"^barcodes/", include("barcodes.urls")),
    url(r"^flowcells/", include("flowcells.urls")),
    ## Local Apps API
    url(r"^api/", include("digestiflow.api_urls")),
    # The rendered Sphinx-based manual.
    url(r"^manual/", include("docs.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.FILEBOXES_ENABLED:
    urlpatterns += [
        url(r"fileboxes/", include("fileboxes.urls")),
    ]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r"^400/$", default_views.bad_request, kwargs={"exception": Exception("Bad Request!")}),
        url(
            r"^403/$",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        url(
            r"^404/$",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        url(r"^500/$", default_views.server_error),
    ]

    urlpatterns += staticfiles_urlpatterns()

    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [url(r"^__debug__/", include(debug_toolbar.urls))] + urlpatterns

barcodes/forms.py
"""Forms for the barcodes app."""

# TODO: add validation for entries JSON?

import json

from django import forms

from digestiflow.utils import model_to_dict, HorizontalFormHelper
from .models import BarcodeSet


class BarcodeSetForm(forms.ModelForm):
    """Form for creating and updating ``BarcodeSet`` records."""

    entries_json = forms.CharField(widget=forms.HiddenInput())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Fill hidden field with JSON value based on the instance's objects.s
        initial_value = []
        for entry in self.instance.entries.all():
            val = model_to_dict(entry, exclude=("pk",), rename={"sodar_uuid": "uuid"})
            val["aliases"] = ",".join(val["aliases"])
            initial_value.append(val)
        self.fields["entries_json"] = forms.CharField(
            widget=forms.HiddenInput(), initial=json.dumps(initial_value)
        )
        # Setup crispy-forms helper
        self.helper = HorizontalFormHelper()

    class Meta:
        model = BarcodeSet
        fields = ("name", "short_name", "description", "set_type", "entries_json")
        widgets = {"description": forms.Textarea(attrs={"rows": 3})}

barcodes/api/views.py
"""API Views for the sequencers app."""

from rest_framework.generics import ListCreateAPIView, RetrieveAPIView, RetrieveUpdateDestroyAPIView

from digestiflow.utils import ProjectMixin, SodarObjectInProjectPermissions
from ..models import BarcodeSet, BarcodeSetEntry
from .serializers import BarcodeSetSerializer, BarcodeSetEntrySerializer


class BarcodeSetViewMixin(ProjectMixin):
    """Common behaviour of BarcodeSet API views."""

    def get_serializer_context(self):
        result = super().get_serializer_context()
        result["project"] = self.get_project()
        return result

    def get_queryset(self):
        return BarcodeSet.objects.filter(project=self.get_project())


class BarcodeSetCreateApiView(BarcodeSetViewMixin, ListCreateAPIView):
    permission_classes = (SodarObjectInProjectPermissions,)
    serializer_class = BarcodeSetSerializer

    def perform_create(self, serializer):
        serializer.save(project=self.get_project())


class BarcodeSetUpdateDestroyApiView(BarcodeSetViewMixin, RetrieveUpdateDestroyAPIView):
    permission_classes = (SodarObjectInProjectPermissions,)
    serializer_class = BarcodeSetSerializer
    lookup_url_kwarg = "barcodeset"
    lookup_field = "sodar_uuid"


class BarcodeSetEntryApiViewMixin(ProjectMixin):
    """Common functionality for BarcodeSetEntry API views."""

    def get_barcode_set(self):
        return BarcodeSet.objects.filter(project=self.get_project()).get(
            sodar_uuid=self.kwargs["barcodeset"]
        )

    def get_serializer_context(self):
        result = super().get_serializer_context()
        result["project"] = self.get_project()
        result["barcode_set"] = self.get_barcode_set()
        return result

    def get_queryset(self):
        return BarcodeSetEntry.objects.filter(barcode_set=self.get_barcode_set())


class BarcodeSetEntryCreateApiView(BarcodeSetEntryApiViewMixin, ListCreateAPIView):
    permission_classes = (SodarObjectInProjectPermissions,)
    serializer_class = BarcodeSetEntrySerializer
    lookup_url_kwarg = "barcodesetentry"
    lookup_field = "sodar_uuid"


class BarcodeSetEntryUpdateDestroyApiView(
    BarcodeSetEntryApiViewMixin, RetrieveUpdateDestroyAPIView
):
    permission_classes = (SodarObjectInProjectPermissions,)
    serializer_class = BarcodeSetEntrySerializer
    lookup_url_kwarg = "barcodesetentry"
    lookup_field = "sodar_uuid"


class BarcodeSetEntryRetrieveApiView(ProjectMixin, RetrieveAPIView):
    permission_classes = (SodarObjectInProjectPermissions,)
    serializer_class = BarcodeSetEntrySerializer
    lookup_url_kwarg = "barcodesetentry"
    lookup_field = "sodar_uuid"

    def get_queryset(self):
        return BarcodeSetEntry.objects.filter(barcode_set__project=self.get_project())

barcodes/views.py
"""The views for the barcodes app."""

import json

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.db import transaction
from django.db.models import ProtectedError
from django.shortcuts import reverse
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView
from projectroles.plugins import get_backend_api
from projectroles.views import LoggedInPermissionMixin, ProjectContextMixin
from django.core.validators import ValidationError

from digestiflow.utils import model_to_dict, ProjectPermissionMixin
from .forms import BarcodeSetForm
from .models import BarcodeSet, BarcodeSetEntry


class BarcodeSetListView(
    LoginRequiredMixin,
    LoggedInPermissionMixin,
    ProjectPermissionMixin,
    ProjectContextMixin,
    ListView,
):
    """Display list of all BarcodeSet records"""

    template_name = "barcodes/barcodeset_list.html"
    permission_required = "barcodes.view_barcodeset"

    model = BarcodeSet
    paginate_by = 10

    def get_queryset(self):
        return (
            super()
            .get_queryset()
            .filter(project__sodar_uuid=self.kwargs["project"])
            .prefetch_related("project")
        )


class BarcodeSetDetailView(
    LoginRequiredMixin,
    LoggedInPermissionMixin,
    ProjectPermissionMixin,
    ProjectContextMixin,
    DetailView,
):
    """Display detail of BarcodeSet records"""

    template_name = "barcodes/barcodeset_detail.html"
    permission_required = "barcodes.view_barcodeset"

    model = BarcodeSet

    slug_url_kwarg = "barcodeset"
    slug_field = "sodar_uuid"


class BarcodeSetCreateView(
    SuccessMessageMixin,
    LoginRequiredMixin,
    LoggedInPermissionMixin,
    ProjectPermissionMixin,
    ProjectContextMixin,
    CreateView,
):
    """Display list of all BarcodeSet records"""

    success_message = "Barcode set successfully created."
    template_name = "barcodes/barcodeset_create.html"
    permission_required = "barcodes.add_barcodeset"

    model = BarcodeSet
    form_class = BarcodeSetForm

    @transaction.atomic
    def form_valid(self, form):
        # Properly set the reference to the current project.
        form.instance.project = self.get_project(self.request, self.kwargs)
        # Save form, get ``self.object``, ready for creating barcode set entries.
        self.object = form.save()
        for entry in json.loads(form.cleaned_data["entries_json"]):
            BarcodeSetEntry.objects.create(
                barcode_set=self.object,
                name=entry["name"],
                aliases=[x.strip() for x in entry["name"].split(",")],
                sequence=entry["sequence"],
            )
        # Call into super class.
        result = super().form_valid(form)
        # Register event with timeline.
        timeline = get_backend_api("timeline_backend")
        if timeline:
            tl_event = timeline.add_event(
                project=self.get_project(self.request, self.kwargs),
                app_name="barcodes",
                user=self.request.user,
                event_name="barcodeset_create",
                description="create barcodeset {barcodeset}: {extra-barcodeset_dict}",
                status_type="OK",
                extra_data={
                    "barcodeset_dict": {
                        **model_to_dict(self.object),
                        "entries": [model_to_dict(entry) for entry in self.object.entries.all()],
                    }
                },
            )
            tl_event.add_object(obj=self.object, label="barcodeset", name=self.object.name)
        return result


class BarcodeSetUpdateView(
    SuccessMessageMixin,
    LoginRequiredMixin,
    LoggedInPermissionMixin,
    ProjectPermissionMixin,
    ProjectContextMixin,
    UpdateView,
):
    """Updating of BarcodeSet records"""

    success_message = "Barcode set successfully updated."
    template_name = "barcodes/barcodeset_update.html"
    permission_required = "barcodes.change_barcodeset"

    model = BarcodeSet
    form_class = BarcodeSetForm

    slug_url_kwarg = "barcodeset"
    slug_field = "sodar_uuid"

    @transaction.atomic
    def form_valid(self, form):
        # Save form, get ``self.object``, ready for updating barcode set entries.
        self.object = form.save()
        try:
            self._update_entries(self.object, form)
        except ValidationError as e:
            messages.error(
                self.request, "Problem updating barcode set: %s" % ", ".join(map(str, e))
            )
            return self.form_invalid(form)
        except ProtectedError as e:  # pragma: no cover
            messages.error(self.request, "Could not update barcode set entries: %s" % e)
            return self.form_invalid(form)
        # Call into super class.
        result = super().form_valid(form)
        # Register event with timeline.
        timeline = get_backend_api("timeline_backend")
        if timeline:
            tl_event = timeline.add_event(
                project=self.get_project(self.request, self.kwargs),
                app_name="barcodes",
                user=self.request.user,
                event_name="barcodeset_update",
                description="update barcodeset {barcodeset}: {extra-barcodeset_dict}",
                status_type="OK",
                extra_data={
                    "barcodeset_dict": {
                        **model_to_dict(self.object),
                        "entries": [model_to_dict(entry) for entry in self.object.entries.all()],
                    }
                },
            )
            tl_event.add_object(obj=self.object, label="barcodeset", name=self.object.name)
        return result

    def _update_entries(self, barcode_set, form):
        """Update barcode set entries of ``barcode_set`` record from JSON field.

        This method must be called within a transaction, of course.

        The algorithm for matching them is also mirrored in the JavaScript and both need to be kept in sync.
        """
        # Existing entries and to-be-updated values by UUID.
        existing = {str(entry.sodar_uuid): entry for entry in barcode_set.entries.all()}
        updated = json.loads(form.cleaned_data["entries_json"])
        for rank, entry in enumerate(updated):
            entry["rank"] = rank
        updated_by_uuid = {entry.get("uuid"): entry for entry in updated if entry.get("uuid")}
        # Delete and update existing.
        for entry in existing.values():
            if str(entry.sodar_uuid) not in updated_by_uuid:
                # Delete records from existing set that we don't find in updated records.
                entry.delete()
            else:
                # Update existing record.
                the_updated = updated_by_uuid[str(entry.sodar_uuid)]
                entry.rank = the_updated["rank"]
                entry.name = the_updated["name"]
                entry.aliases = [x.strip() for x in the_updated.get("aliases", "").split(",")]
                entry.sequence = the_updated["sequence"]
                entry.save()
        # Add new records.
        for entry in updated:
            if not entry.get("uuid") or entry.get("uuid") not in existing:
                BarcodeSetEntry.objects.create(
                    rank=entry["rank"],
                    name=entry["name"],
                    aliases=[x.strip() for x in entry.get("aliases", "").split(",")],
                    sequence=entry["sequence"],
                    barcode_set=barcode_set,
                )


class BarcodeSetDeleteView(
    SuccessMessageMixin,
    LoginRequiredMixin,
    LoggedInPermissionMixin,
    ProjectPermissionMixin,
    ProjectContextMixin,
    DeleteView,
):
    """Deletion of BarcodeSet records"""

    success_message = "Barcode set successfully deleted."
    template_name = "barcodes/barcodeset_confirm_delete.html"
    permission_required = "barcodes.delete_barcodeset"

    model = BarcodeSet

    slug_url_kwarg = "barcodeset"
    slug_field = "sodar_uuid"

    @transaction.atomic
    def delete(self, *args, **kwargs):
        # Delete barcode set record.
        for entry in self.get_object().entries.all():
            entry.delete()
        result = super().delete(*args, **kwargs)
        # Register event with timeline.
        timeline = get_backend_api("timeline_backend")
        if timeline:
            tl_event = timeline.add_event(
                project=self.get_project(self.request, self.kwargs),
                app_name="barcodes",
                user=self.request.user,
                event_name="barcodeset_delete",
                description="delete barcodeset {barcodeset}: {extra-barcodeset_dict}",
                status_type="OK",
                extra_data={
                    "barcodeset_dict": {
                        **model_to_dict(self.object),
                        "entries": [model_to_dict(entry) for entry in self.object.entries.all()],
                    }
                },
            )
            tl_event.add_object(obj=self.object, label="barcodeset", name=self.object.name)
        return result

    def get_success_url(self):
        return reverse(
            "barcodes:barcodeset-list",
            kwargs={"project": self.get_project(self.request, self.kwargs).sodar_uuid},
        )

barcodes/templates/barcodes/_barcodeset_create_update.html
{% extends "projectroles/project_base.html" %}

{% load crispy_forms_tags %}
{% load static %}

{% block navi_sub_project_extend %}
  <li class="breadcrumb-item">
    <a href="{% url 'barcodes:barcodeset-list' project=project.sodar_uuid %}">Barcode Set</a>
  </li>
  {% if object.pk %}
    <li class="breadcrumb-item">
      <a href="{% url 'barcodes:barcodeset-detail' project=project.sodar_uuid barcodeset=object.sodar_uuid %}">
        {{ object.name }} ({{ object.short_name }})
      </a>
    </li>
    <li class="breadcrumb-item active">
      Update
    </li>
  {% else %}
    <li class="breadcrumb-item active">
      Create
    </li>
  {% endif %}
{% endblock %}

{% block title %}
  {% if object.pk %}
    Updating {{ object.name }} ({{ vendor.short_name }})
  {% else %}
    Create new Barcode Set in {{ project.title }}
  {% endif %}
{% endblock title %}

{% block projectroles %}
  <div class="row sodar-pr-content-title pb-2">
    {# Project menu dropdown, only visible if browser width < X and sidebar is hidden #}
    {% include 'projectroles/_project_menu_btn.html' %}

    <h2 class="sodar-pr-content-title">
      {% if object.pk %}
        Update
      {% else %}
        Create
      {% endif %}
      Barcode Set
    </h2>
  </div>

  <div class="container-fluid sodar-page-container">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a class="nav-link active" id="properties-tab" data-toggle="tab" href="#properties" aria-controls="properties" aria-selected="true">Properties</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="barcodes-tab" data-toggle="tab" href="#barcodes" aria-controls="barcodes" aria-selected="true">Barcodes</a>
      </li>
    </ul>

    <form method="post">{% csrf_token %}
      <div class="tab-content border-left border-right border-bottom" id="flowcellTabContent">
        <div class="tab-pane show active" id="properties" role="tabpanel" aria-labelledby="properties-tab">
          <div class="row py-3">
            <div class="col">
              {% if object.pk %}
                <div class="form-group row">
                  <label class="form-control-label {{ form.helper.label_class }}">UUID</label>
                  <div class="{{ form.helper.field_class}}">
                    <input type="text" readonly class="form-control-plaintext" value="{{ object.sodar_uuid }}">
                  </div>
                </div>
                <div class="form-group row">
                  <label class="form-control-label {{ form.helper.label_class }}">Project</label>
                  <div class="{{ form.helper.field_class}}">
                    <input type="text" readonly class="form-control-plaintextt" value="{{ object.project.title }}">
                  </div>
                </div>
                <div class="form-group row">
                  <label class="form-control-label {{ form.helper.label_class }}">Created</label>
                  <div class="{{ form.helper.field_class}}">
                    <input type="text" readonly class="form-control-plaintext" value="{{ object.date_created }}">
                  </div>
                </div>
                <div class="form-group row">
                  <label class="form-control-label {{ form.helper.label_class }}">Last Update</label>
                  <div class="{{ form.helper.field_class}}">
                    <input type="text" readonly class="form-control-plaintext" value="{{ object.date_modified }}">
                  </div>
                </div>
              {% endif %}

              {% crispy form form.helper %}

              {% include "barcodes/_barcodeset_submit_buttons.html" %}
            </div>
          </div>
        </div>
        <div class="tab-pane fade" id="barcodes" role="tabpanel" aria-labelledby="barcodes-tab">
          <div class="row py-3">
            <div class="col">
              <p class="text-muted text-small">
                Enter the barcode names and sequences.
                In the case of paired indexing, enter the sequence of the second sequence as in &quot;Workflow A&quot;.
                That is, enter it as it has to be entered for MiSeq, HiSeq 2000, HiSeq 2500, or NovaSeq 6000.
                DigestiFlow will automatically use the index as entered or its reverse complement based on the properties of the sequencing machine used.
              </p>
              <p class="text-muted text-small">
                <i class="iconify" data-icon="mdi:information"></i>
                The <strong>context menu</strong> allows you to easily <strong>reverse-complement</strong> sequences.
              </p>

              <div class="row">
                <div id="grid-container" class="col-6 pl-0 pr-2" class="barcodeset-table-container">
                  <div id="barcodeSetEntryGrid"></div>
                </div>
                <div class="col-6">
                  <div id="preview" style="height:200x;">
                    <div style="height: 100%; width: 100%; overflow: auto;">
                      <h6>Action preview</h6>
                      <div id="id-action-preview"></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col pt-3">
              {% include "barcodes/_barcodeset_submit_buttons.html" %}
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>
{% endblock %}


{% block javascript %}
  {{ block.super }}
  <script type="text/javascript" src="{% static 'js/vendor/sheetclip-0.2.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/handsontable.full.min.js' %}"></script>
  <link rel="stylesheet" type="text/css" href="{% static 'css/handsontable.full.min.css' %}">

  <script type="text/javascript" charset="utf-8">
    {% include "barcodes/_script_barcodeset_editor.js" %}
  </script>
{% endblock %}

barcodes/templates/barcodes/_barcodeset_detail_buttons.html
<div class="btn-group ml-auto" id="sodar-ff-buttons-list">
  <button class="btn btn-primary dropdown-toggle"
          type="button" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
    Barcode Set Operations
  </button>
  <div class="dropdown-menu dropdown-menu-right">
    <a class="dropdown-item" href="{% url 'barcodes:barcodeset-create' project=project.sodar_uuid %}">
      <i class="iconify" data-icon="mdi:plus-thick"></i> Create New
    </a>
    <a class="dropdown-item" href="{% url 'barcodes:barcodeset-update' project=project.sodar_uuid barcodeset=object.sodar_uuid %}">
      <i class="iconify" data-icon="mdi:lead-pencil"></i> Update
    </a>
    <a class="dropdown-item" href="{% url 'barcodes:barcodeset-delete' project=project.sodar_uuid barcodeset=object.sodar_uuid %}">
      <i class="iconify" data-icon="mdi:close-thick"></i> Delete
    </a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="{% url 'api:barcodesets' project=project.sodar_uuid barcodeset=object.sodar_uuid %}?format=json">
      <i class="iconify" data-icon="mdi:cloud-download"></i> JSON Export
    </a>
  </div>
</div>

barcodes/templates/barcodes/_barcodeset_item_buttons.html
<div class="btn-group sodar-list-btn-group pull-right">
  <button class="btn btn-secondary dropdown-toggle sodar-list-dropdown"
      type="button" data-toggle="dropdown" aria-expanded="false">
    <i class="iconify" data-icon="mdi:cog"></i>
  </button>
  <div class="dropdown-menu dropdown-menu-right">
    <a class="dropdown-item" href="{% url 'barcodes:barcodeset-update' project=project.sodar_uuid barcodeset=item.sodar_uuid %}">
      <i class="iconify" data-icon="mdi:lead-pencil"></i>
      Update
    </a>
    <a class="dropdown-item" href="{% url 'barcodes:barcodeset-delete' project=project.sodar_uuid barcodeset=item.sodar_uuid %}">
      <i class="iconify" data-icon="mdi:close-thick"></i>
      Delete
    </a>
  </div>
</div>

barcodes/templates/barcodes/_barcodeset_list_buttons.html
<div class="btn-group ml-auto" id="sodar-ff-buttons-list">
  <button class="btn btn-primary dropdown-toggle"
          type="button" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
    Barcode Set Operations
  </button>
  <div class="dropdown-menu dropdown-menu-right">
    <a class="dropdown-item" href="{% url 'barcodes:barcodeset-create' project=project.sodar_uuid %}">
      <i class="iconify" data-icon="mdi:plus-thick"></i> Create
    </a>
  </div>
</div>

barcodes/templates/barcodes/_barcodeset_submit_buttons.html
<div class="text-right my-3">
  <div class="btn-group" role="group">
    <a role="button" class="btn btn-secondary"
      {% if object.pk %}
        href="{% url 'barcodes:barcodeset-detail' project=project.sodar_uuid barcodeset=object.sodar_uuid %}">
      {% else %}
        href="{% url 'barcodes:barcodeset-list' project=project.sodar_uuid %}">
      {% endif %}
      <i class="iconify" data-icon="mdi:arrow-left-circle"></i>
      Cancel
    </a>
    <button type="submit" class="btn btn-primary">
      <i class="iconify" data-icon="mdi:check-bold"></i>
      {% if object.pk %}
        Update
      {% else %}
        Create
      {% endif %}
    </button>
  </div>
</div>

barcodes/templates/barcodes/_search_item.html
{# Projectroles dependency #}
{% load projectroles_common_tags %}

<tr class="sodar-ff-search-item" id="sodar-ff-search-item-{{ item.sodar_uuid }}">
  {# Name & link column #}
  <td>
    <div class="sodar-overflow-container">
      <a href="{{ item.get_absolute_url }}">
        {% autoescape off %}
          {% if item.project %}
            {% highlight_search_term item.name search_term %} ({% highlight_search_term item.short_name search_term %})
          {% else %}
            {% highlight_search_term item.name search_term %} ({% highlight_search_term item.sequence search_term %})
          {% endif %}
        {% endautoescape %}
      </a>
    </div>
  </td>
  <td>
    {% if item.barcode_set %}
      Barcode
    {% else %}
      Barcode Set
    {% endif %}
  </td>
  {# Project column #}
  <td>
    <div class="sodar-overflow-container">
      {% autoescape off %}
        {% if item.project %}
          <a href="{% url 'projectroles:detail' project=item.project.sodar_uuid %}">
            {{ item.project.title }}
          </a>
        {% else %}
          <a href="{% url 'projectroles:detail' project=item.barcode_set.project.sodar_uuid %}">
            {% highlight_search_term item.barcode_set.project.title search_term %}
          </a>
          /
          <a href="{% url 'barcodes:barcodeset-detail' project=item.barcode_set.project.sodar_uuid barcodeset=item.barcode_set.sodar_uuid %}">
            {% highlight_search_term item.barcode_set.name search_term %}
            ({% highlight_search_term item.barcode_set.short_name search_term %})
          </a>
        {% endif %}
      {% endautoescape %}
    </div>
  </td>
</tr>

barcodes/templates/barcodes/barcodeset_update.html
{% include "barcodes/_barcodeset_create_update.html" %}