barcodes/urls.py
from django.conf.urls import url
from . import views

app_name = "barcodes"

urlpatterns = [
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/barcodeset/$",
        view=views.BarcodeSetListView.as_view(),
        name="barcodeset-list",
    ),
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/barcodeset/create$",
        view=views.BarcodeSetCreateView.as_view(),
        name="barcodeset-create",
    ),
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/barcodeset/(?P<barcodeset>[0-9a-f-]+)/$",
        view=views.BarcodeSetDetailView.as_view(),
        name="barcodeset-detail",
    ),
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/barcodeset/(?P<barcodeset>[0-9a-f-]+)/update$",
        view=views.BarcodeSetUpdateView.as_view(),
        name="barcodeset-update",
    ),
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/barcodeset/(?P<barcodeset>[0-9a-f-]+)/delete$",
        view=views.BarcodeSetDeleteView.as_view(),
        name="barcodeset-delete",
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.shortcuts import render
from django.views import defaults as default_views
from django.views.generic import TemplateView

from projectroles.views import HomeView
from sentry_sdk import last_event_id


def handler500(request, *args, **argv):
    return render(request, "500.html", {"sentry_event_id": last_event_id()}, status=500)


urlpatterns = [
    url(r"^$", HomeView.as_view(), name="home"),
    url(r"^about/$", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),
    # Login and logout
    url(r"^login/$", auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    url(r"^logout/$", auth_views.logout_then_login, name="logout"),
    # Auth
    url(r"api/auth/", include("knox.urls")),
    # Iconify SVG icons
    url(r"icons/", include("dj_iconify.urls")),
    ## SODAR Core
    # Projectroles URLs
    url(r"^project/", include("projectroles.urls")),
    # Filesfolders URLs
    url(r"^filesfolders/", include("filesfolders.urls")),
    # django-db-file-storage URLs (needed for admin, obfuscated for users)
    url(r"^xu7in5zs9lylar0n/", include("db_file_storage.urls")),
    # Timeline URLs
    url(r"^timeline/", include("timeline.urls")),
    # User Profile URLs
    url(r"^user/", include("userprofile.urls")),
    # Admin Alerts URLs
    url(r"^alerts/", include("adminalerts.urls")),
    # Background jobs URLs
    url(r"^bgjobs/", include("bgjobs.urls")),
    # Site Info URLs
    url(r"^siteinfo/", include("siteinfo.urls")),
    # API Tokens URLs
    url(r"^tokens/", include("tokens.urls")),
    ## Local Apps
    url(r"^sequencers/", include("sequencers.urls")),
    url(r"^barcodes/", include("barcodes.urls")),
    url(r"^flowcells/", include("flowcells.urls")),
    ## Local Apps API
    url(r"^api/", include("digestiflow.api_urls")),
    # The rendered Sphinx-based manual.
    url(r"^manual/", include("docs.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.FILEBOXES_ENABLED:
    urlpatterns += [
        url(r"fileboxes/", include("fileboxes.urls")),
    ]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r"^400/$", default_views.bad_request, kwargs={"exception": Exception("Bad Request!")}),
        url(
            r"^403/$",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        url(
            r"^404/$",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        url(r"^500/$", default_views.server_error),
    ]

    urlpatterns += staticfiles_urlpatterns()

    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [url(r"^__debug__/", include(debug_toolbar.urls))] + urlpatterns

flowcells/urls.py
from django.conf.urls import url
from . import views

app_name = "flowcells"

urlpatterns = [
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/flowcell/$",
        view=views.FlowCellListView.as_view(),
        name="flowcell-list",
    ),
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/flowcell/create$",
        view=views.FlowCellCreateView.as_view(),
        name="flowcell-create",
    ),
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/flowcell/(?P<flowcell>[0-9a-f-]+)/$",
        view=views.FlowCellDetailView.as_view(),
        name="flowcell-detail",
    ),
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/flowcell/(?P<flowcell>[0-9a-f-]+)/update/$",
        view=views.FlowCellUpdateView.as_view(),
        name="flowcell-update",
    ),
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/flowcell/(?P<flowcell>[0-9a-f-]+)/delete/$",
        view=views.FlowCellDeleteView.as_view(),
        name="flowcell-delete",
    ),
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/message/(?P<flowcell>[0-9a-f-]+)/create/$",
        view=views.MessageCreateView.as_view(),
        name="message-create",
    ),
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/message/(?P<flowcell>[0-9a-f-]+)/update/(?P<message>[0-9a-f-]+)/$",
        view=views.MessageUpdateView.as_view(),
        name="message-update",
    ),
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/message/(?P<flowcell>[0-9a-f-]+)/delete/(?P<message>[0-9a-f-]+)/$",
        view=views.MessageDeleteView.as_view(),
        name="message-delete",
    ),
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/flowcell/(?P<flowcell>[0-9a-f-]+)/update-status/(?P<attribute>[a-z_]+)/$",
        view=views.FlowCellUpdateStatusView.as_view(),
        name="flowcell-update-status",
    ),
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/flowcell/(?P<flowcell>[0-9a-f-]+)/toggle-watching/$",
        view=views.FlowCellToggleWatchingView.as_view(),
        name="flowcell-toggle-watching",
    ),
    url(
        regex=(
            r"^(?P<project>[0-9a-f-]+)/flowcell/(?P<flowcell>[0-9a-f-]+)/suppress-warning/"
            r"(?P<warning>no_sample_sheet|no_sample_found_for_observed_index)/(?P<lanes>[0-9]+(?:,[0-9]+)*)/$"
        ),
        view=views.FlowCellSuppressWarningView.as_view(),
        name="flowcell-suppress-warning",
    ),
    url(
        regex=(
            r"^(?P<project>[0-9a-f-]+)/flowcell/(?P<flowcell>[0-9a-f-]+)/suppress-warning/"
            r"(?P<library>[0-9a-f-]+)/(?P<barcode_no>[12])/$"
        ),
        view=views.LibrarySuppressWarningView.as_view(),
        name="library-suppress-warning",
    ),
]

sequencers/urls.py
from django.conf.urls import url
from . import views

app_name = "sequencers"

urlpatterns = [
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/sequencer/$",
        view=views.SequencingMachineListView.as_view(),
        name="sequencer-list",
    ),
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/sequencer/create$",
        view=views.SequencingMachineCreateView.as_view(),
        name="sequencer-create",
    ),
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/sequencer/(?P<sequencer>[0-9a-f-]+)/$",
        view=views.SequencingMachineDetailView.as_view(),
        name="sequencer-detail",
    ),
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/sequencer/(?P<sequencer>[0-9a-f-]+)/update$",
        view=views.SequencingMachineUpdateView.as_view(),
        name="sequencer-update",
    ),
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/sequencer/(?P<sequencer>[0-9a-f-]+)/delete$",
        view=views.SequencingMachineDeleteView.as_view(),
        name="sequencer-delete",
    ),
]

flowcells/api/views.py
"""API Views for the flowcells app."""

from django.shortcuts import get_object_or_404
from projectroles.models import Project
from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet
from rest_framework.parsers import MultiPartParser

from digestiflow.utils import ProjectMixin, SodarObjectInProjectPermissions
from ..models import (
    FlowCell,
    LaneIndexHistogram,
    Message,
    flow_cell_created,
    flow_cell_updated,
    message_created,
    MSG_STATE_SENT,
    MSG_STATE_DRAFT,
)
from .serializers import (
    FlowCellSerializer,
    LaneIndexHistogramSerializer,
    MessageSerializer,
    AttachmentSerializer,
)

# TODO: authorization still missing, need mixin for this!


class FlowCellApiViewMixin(ProjectMixin):
    """Common behaviour of FlowCell API views."""

    def get_serializer_context(self):
        result = super().get_serializer_context()
        result["project"] = self.get_project()
        return result

    def get_queryset(self):
        return FlowCell.objects.filter(project=self.get_project()).prefetch_related(
            "index_histograms",
            "messages",
            "libraries",
            "libraries__barcode",
            "libraries__barcode__barcode_set",
            "libraries__barcode2",
            "libraries__barcode2__barcode_set",
        )


class FlowCellListCreateApiView(FlowCellApiViewMixin, ListCreateAPIView):
    permission_classes = (SodarObjectInProjectPermissions,)
    serializer_class = FlowCellSerializer

    def get_queryset(self):
        """Restrict flow cells to those with a sequencing, processing, or delivery state from query string.

        For this, the query parameters "sequencing_status", "conversion_status", and "delivery_status" are interpreted.
        """
        queryset = super().get_queryset().all()
        for token in ("sequencing", "conversion", "delivery"):
            key = "status_%s" % token
            status = self.request.query_params.get(key, None)
            if status:
                queryset = queryset.filter(**{key: status})
        return queryset

    def perform_create(self, serializer):
        super().perform_create(serializer)
        flow_cell_created(serializer.instance)


class FlowCellUpdateDestroyApiView(FlowCellApiViewMixin, RetrieveUpdateDestroyAPIView):
    permission_classes = (SodarObjectInProjectPermissions,)
    serializer_class = FlowCellSerializer
    lookup_url_kwarg = "flowcell"
    lookup_field = "sodar_uuid"

    def perform_update(self, serializer):
        original = FlowCell.objects.get(pk=serializer.instance.pk)
        super().perform_update(serializer)
        flow_cell_updated(original, serializer.instance)


class FlowCellResolveApiView(FlowCellApiViewMixin, ModelViewSet):
    """Resolve flow cell attributes to UUID"""

    permission_classes = (SodarObjectInProjectPermissions,)
    serializer_class = FlowCellSerializer

    def resolve(self, _request, project, instrument_id, run_no, flowcell_id):
        project = Project.objects.get(sodar_uuid=project)
        flowcell = get_object_or_404(
            FlowCell.objects.filter(project=project),
            sequencing_machine__vendor_id=instrument_id,
            run_number=run_no,
            vendor_id=flowcell_id,
        )
        # Because this does not fit list_route or detail_route, we have to check permissions manually.
        return Response(self.get_serializer(flowcell).data)


class LaneIndexHistogramApiViewMixin(ProjectMixin):
    """Common functionality for LaneIndexHistogram API views."""

    def get_flowcell(self):
        return FlowCell.objects.filter(project=self.get_project()).get(
            sodar_uuid=self.kwargs["flowcell"]
        )

    def get_serializer_context(self):
        result = super().get_serializer_context()
        result["project"] = self.get_project()
        result["flowcell"] = self.get_flowcell()
        return result

    def get_queryset(self):
        return LaneIndexHistogram.objects.filter(flowcell=self.get_flowcell())


class LaneIndexHistogramListCreateApiView(LaneIndexHistogramApiViewMixin, ListCreateAPIView):
    permission_classes = (SodarObjectInProjectPermissions,)
    serializer_class = LaneIndexHistogramSerializer


class LaneIndexHistogramUpdateDestroyApiView(
    LaneIndexHistogramApiViewMixin, RetrieveUpdateDestroyAPIView
):
    permission_classes = (SodarObjectInProjectPermissions,)
    serializer_class = LaneIndexHistogramSerializer
    lookup_url_kwarg = "indexhistogram"
    lookup_field = "sodar_uuid"


class MessageApiViewMixin(ProjectMixin):
    """Common functionality for Message API views."""

    def get_flowcell(self):
        return FlowCell.objects.filter(project=self.get_project()).get(
            sodar_uuid=self.kwargs["flowcell"]
        )

    def get_serializer_context(self):
        result = super().get_serializer_context()
        result["project"] = self.get_project()
        result["flowcell"] = self.get_flowcell()
        return result

    def get_queryset(self):
        return Message.objects.filter(flow_cell=self.get_flowcell())


class MessageListCreateApiView(MessageApiViewMixin, ListCreateAPIView):
    permission_classes = (SodarObjectInProjectPermissions,)
    serializer_class = MessageSerializer

    def perform_create(self, serializer):
        super().perform_create(serializer)
        message_created(serializer.instance)


class MessageUpdateDestroyApiView(MessageApiViewMixin, RetrieveUpdateDestroyAPIView):
    permission_classes = (SodarObjectInProjectPermissions,)
    serializer_class = MessageSerializer
    lookup_url_kwarg = "message"
    lookup_field = "sodar_uuid"

    def perform_update(self, serializer):
        original = Message.objects.get(pk=serializer.instance.pk)
        super().perform_update(serializer)
        if original.state == MSG_STATE_DRAFT and serializer.instance.state == MSG_STATE_SENT:
            message_created(serializer.instance)


class AttachmentApiViewMixin(ProjectMixin):
    """Common functionality for filesfolders File attachment API views."""

    def get_flowcell(self):
        return FlowCell.objects.filter(project=self.get_project()).get(
            sodar_uuid=self.kwargs["flowcell"]
        )

    def get_message(self):
        flow_cell = self.get_flowcell()
        return flow_cell.messages.get(sodar_uuid=self.kwargs["message"])

    def get_serializer_context(self):
        result = super().get_serializer_context()
        result["project"] = self.get_project()
        result["flowcell"] = self.get_flowcell()
        result["message"] = self.get_message()
        return result

    def get_queryset(self):
        return self.get_message().get_attachment_files()


class AttachmentListApiView(AttachmentApiViewMixin, ListCreateAPIView):
    parser_classes = (MultiPartParser,)
    permission_classes = (SodarObjectInProjectPermissions,)
    serializer_class = AttachmentSerializer


class AttachmentRetrieveApiView(AttachmentApiViewMixin, RetrieveUpdateDestroyAPIView):
    parser_classes = (MultiPartParser,)
    permission_classes = (SodarObjectInProjectPermissions,)
    serializer_class = AttachmentSerializer
    lookup_url_kwarg = "file"
    lookup_field = "sodar_uuid"

flowcells/templates/flowcells/_flowcell_messages.html
{% load crispy_forms_tags %}
{% load humanize %}

{# TODO: display non-draft message or message from user #}
<div class="row" id="messages-top">
  <div class="col px-0">
    {% if object.get_sent_messages %}
      {% for message in object.get_sent_messages %}
        {% include "flowcells/_message_item.html" %}
      {% endfor %}
    {% else %}
      <p class="text-center font-italic">
        No messages (yet).
      </p>
    {% endif %}
  </div>
</div>

<div class="row">
  <div class="col px-0">
    <div class="card card-body bg-light">
      <h5 class="card-title">Write Message</h5>

      {% if message_form.instance.pk %}
        <span id="{{ message_form.instance.sodar_uuid }}"></span>
      {% endif %}
      <form id="message-form" method="post" enctype="multipart/form-data"
          {% if message_form.instance.pk %}
            action="{% url 'flowcells:message-update' project=project.sodar_uuid flowcell=object.sodar_uuid message=message_form.instance.sodar_uuid %}#message-form"
          {% else %}
            action="{% url 'flowcells:message-create' project=project.sodar_uuid flowcell=object.sodar_uuid %}#message-form"
          {% endif %}
        >{% csrf_token %}
        {% if message_form.instance.pk %}
        <p class="alert alert-info">
          <i class="iconify pr-2" data-icon="mdi:information"></i>
          Your message has been saved as a draft.
          Only you can see it.
          Use Send below for actually sending it.
        </p>
        {% endif %}

        {% crispy message_form message_form.helper %}

        <div class="text-right pb-3">
          <div class="btn-group" role="group">
            <button type="submit" name="submit" value="discard" class="btn btn-danger">
              <i class="iconify" data-icon="mdi:close-thick"></i>
              Discard
            </button>
            <button type="submit" name="submit" value="save" class="btn btn-secondary">
              <i class="iconify" data-icon="mdi:content-save"></i>
              Save as Draft
            </button>
            <button type="submit" name="submit" value="send" class="btn btn-primary">
              <i class="iconify" data-icon="mdi:send"></i>
              Send
            </button>
          </div>
        </div>
      </form>
    </div>
  </div>
</div>

flowcells/templates/flowcells/_flowcell_properties.html
{% load flowcells %}

<h4>Meta Info</h4>

<dl class="row flowcell-properties">
  <dt class="col-12 col-md-3 col-xl-2">UUID</dt>
  <dd class="col-12 col-md-9 col-xl-10">{{ object.sodar_uuid }}</dd>

  <dt class="col-12 col-md-3 col-xl-2">Site</dt>
  <dd class="col-12 col-md-9 col-xl-10">{{ object.project.title }}</dd>

  <dt class="col-12 col-md-3 col-xl-2">Created</dt>
  <dd class="col-12 col-md-9 col-xl-10">{{ object.date_created }}</dd>

  <dt class="col-12 col-md-3 col-xl-2">Last Modified</dt>
  <dd class="col-12 col-md-9 col-xl-10">{{ object.date_modified }}</dd>
</dl>

<h4>Basic Properties</h4>

<dl class="row flowcell-properties">
  <dt class="col-12 col-md-3 col-xl-2">Full Name</dt>
  <dd class="col-12 col-md-9 col-xl-10">{{ object.get_full_name }}</dd>

  <dt class="col-12 col-md-3 col-xl-2">Sequencer</dt>
  <dd class="col-12 col-md-9 col-xl-10">
    <a href="{% url 'sequencers:sequencer-detail' project=project.sodar_uuid sequencer=object.sequencing_machine.sodar_uuid %}">
      {{ object.sequencing_machine.label }}
      ({{ object.sequencing_machine.vendor_id }})
    </a>
  </dd>

  <dt class="col-12 col-md-3 col-xl-2">Manual Label</dt>
  <dd class="col-12 col-md-9 col-xl-10">{{ object.manual_label|default:"-" }}</dd>

  <dt class="col-12 col-md-3 col-xl-2">Description</dt>
  <dd class="col-12 col-md-9 col-xl-10">{{ object.description|linebreaksbr }}</dd>

  <dt class="col-12 col-md-3 col-xl-2">Number of Lanes</dt>
  <dd class="col-12 col-md-9 col-xl-10">{{ object.num_lanes|default:"-" }}</dd>

  <dt class="col-12 col-md-3 col-xl-2">RTA Version</dt>
  <dd class="col-12 col-md-9 col-xl-10">{{ object.rta_version }}</dd>

  <dt class="col-12 col-md-3 col-xl-2">Planned Reads</dt>
  <dd class="col-12 col-md-9 col-xl-10 text-nowrap">{{ object.planned_reads|format_basemask }}</dd>
</dl>

<h4>Demultiplexing and State</h4>

<dl class="row flowcell-properties">
  <dt class="col-12 col-md-3 col-xl-2">Operator</dt>
  <dd class="col-12 col-md-9 col-xl-10">{{ object.operator|default:"-" }}</dd>

  <dt class="col-12 col-md-3 col-xl-2">Demux Operator</dt>
  <dd class="col-12 col-md-9 col-xl-10">{{ object.demux_operator.name|default:"-" }}</dd>

  <dt class="col-12 col-md-3 col-xl-2">Current Reads</dt>
  <dd class="col-12 col-md-9 col-xl-10">{{ object.current_reads|format_basemask }}</dd>

  <dt class="col-12 col-md-3 col-xl-2">Status Sequencing</dt>
  <dd class="col-12 col-md-9 col-xl-10">{{ object.status_sequencing }}</dd>

  <dt class="col-12 col-md-3 col-xl-2">Status Conversion</dt>
  <dd class="col-12 col-md-9 col-xl-10">{{ object.status_conversion }}</dd>

  <dt class="col-12 col-md-3 col-xl-2">Status Delivery</dt>
  <dd class="col-12 col-md-9 col-xl-10">{{ object.status_delivery }}</dd>

  <dt class="col-12 col-md-3 col-xl-2">Delivery Type</dt>
  <dd class="col-12 col-md-9 col-xl-10">{{ object.delivery_type }}</dd>
</dl>

<h4>Parameters for <code>bcl2fastq</code></h4>

<dl class="row flowcell-properties">
  <dt class="col-12 col-md-3 col-xl-2">Barcode Mismatches</dt>
  <dd class="col-12 col-md-9 col-xl-10">{{ object.barcode_mismatches|default:"-" }}</dd>

  <dt class="col-12 col-md-3 col-xl-2">Manual Demux Reads</dt>
  <dd class="col-12 col-md-9 col-xl-10">{{ object.demux_reads|format_basemask|default:"-" }}</dd>

  <dt class="col-12 col-md-3 col-xl-2">Minimum Trimmed Read Length</dt>
  <dd class="col-12 col-md-9 col-xl-10">{{ object.minimum_trimmed_read_length|default:"-" }}</dd>

  <dt class="col-12 col-md-3 col-xl-2">Mask Short Adapter Reads</dt>
  <dd class="col-12 col-md-9 col-xl-10">{{ object.mask_short_adapter_reads|default:"-" }}</dd>

  <dt class="col-12 col-md-3 col-xl-2">Create FASTQ for Index Reads</dt>
  <dd class="col-12 col-md-9 col-xl-10">{% if form.create_fastq_for_index_reads %}yes{% else %}no{% endif %}</dd>
</dl>

<h4>Sheet Sanity Check and Quality Control</h4>

<dl class="row flowcell-properties">
  <dt class="col-12 col-md-3 col-xl-2">Sheet Completeness</dt>
  <dd class="col-12 col-md-9 col-xl-10">
    {% get_lanes_with_missing_sheets object as lanes_with_missing_sheets %}
    {% if lanes_with_missing_sheets %}
      <span class="text-warning">
        <i class="iconify pr-1" data-icon="mdi:alert-circle" title="Missing sheet info {{ lanes_with_missing_sheets|pluralize:"lane,lanes" }} {{ lanes_with_missing_sheets|pretty_range }}"
           data-toggle="tooltip"
           data-popover-url="{% url 'flowcells:flowcell-suppress-warning' project=project.sodar_uuid flowcell=flowcell.sodar_uuid warning="no_sample_sheet" lanes=lanes_with_missing_sheets|join:"," %}?return_to=properties"></i>
        Sample sheet missing for {{ lanes_with_missing_sheets|pluralize:"lane,lanes" }} {{ lanes_with_missing_sheets|pretty_range }}.
      </span>
    {% elif flowcell.lanes_suppress_no_sample_sheet_warning %}
      {% get_lanes_with_missing_sheets object True as lanes_with_missing_sheets %}
      <span class="text-muted">
        <i class="iconify pr-1" data-icon="mdi:alert-circle" title="Missing sheet info {{ lanes_with_missing_sheets|pluralize:"lane,lanes" }} {{ lanes_with_missing_sheets|pretty_range }}"
           data-toggle="tooltip"
           data-popover-url="{% url 'flowcells:flowcell-suppress-warning' project=project.sodar_uuid flowcell=flowcell.sodar_uuid warning="no_sample_sheet" lanes=lanes_with_missing_sheets|join:"," %}?return_to=properties"></i>
        Suppressed warning {{ lanes_with_missing_sheets|pluralize:"s" }} on lanes with missing sample sheets.
      </span>
    {% else %}
      The sheet is complete
    {% endif %}
  </dd>

  <dt class="col-12 col-md-3 col-xl-2">All BCL indexes in sheet?</dt>
  <dd class="col-12 col-md-9 col-xl-10">
    {% get_index_error_lanes object True as all_lanes_with_index_errors %}
    {% if flowcell.get_index_errors %}
      <span class="text-danger">
        <i class="iconify pr-1" data-icon="mdi:alert-circle" title="Indices not found in sheet"
         data-toggle="tooltip"
         data-popover-url="{% url 'flowcells:flowcell-suppress-warning' project=project.sodar_uuid flowcell=flowcell.sodar_uuid warning="no_sample_found_for_observed_index" lanes=all_lanes_with_index_errors|join:"," %}?return_to=properties"></i>
        At least one index adapter was not found in the sample sheet.
      </span>
    {% elif flowcell.lanes_suppress_no_sample_found_for_observed_index_warning %}
      <span class="text-muted">
        <i class="iconify pr-1" data-icon="mdi:alert-circle" title="Indices not found in sheet"
         data-toggle="tooltip"
         data-popover-url="{% url 'flowcells:flowcell-suppress-warning' project=project.sodar_uuid flowcell=flowcell.sodar_uuid warning="no_sample_found_for_observed_index" lanes=all_lanes_with_index_errors|join:"," %}?return_to=properties"></i>
        Suppressed warnings about BCL index adapters that cannot be found in the sample sheet.
      </span>
    {% else %}
      All (non-contamination) index adapters found in sheet.
    {% endif %}
  </dd>

  <dt class="col-12 col-md-3 col-xl-2">All sheet libraries in BCL?</dt>
  <dd class="col-12 col-md-9 col-xl-10">
    {% get_libraries_with_suppressed_reverse_index_errors object as libraries_with_suppressed_index_errors %}
    {% if flowcell.get_reverse_index_errors %}
      <span class="text-danger">
        <i class="iconify pr-1" data-icon="mdi:alert-circle" title="There is an issue with a library on the sample shet." data-toggle="tooltip"></i>
        There is an issue with a library on the sample shet.
      </span>
    {% elif libraries_with_suppressed_index_errors %}
      <span class="text-muted">
        <i class="iconify pr-1" data-icon="mdi:alert-circle" title="Sheet index library not found in BCLs indices" data-toggle="tooltip"></i>
        Suppressed warnings about sample sheet index adapters that cannot be found in the BCL indices.
      </span>
    {% else %}
      All (non-contamination) index adapters found in sheet.
    {% endif %}
  </dd>
</dl>

flowcells/templates/flowcells/flowcell_create.html
{% include "flowcells/_flowcell_create_update.html" %}