config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.shortcuts import render
from django.views import defaults as default_views
from django.views.generic import TemplateView

from projectroles.views import HomeView
from sentry_sdk import last_event_id


def handler500(request, *args, **argv):
    return render(request, "500.html", {"sentry_event_id": last_event_id()}, status=500)


urlpatterns = [
    url(r"^$", HomeView.as_view(), name="home"),
    url(r"^about/$", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),
    # Login and logout
    url(r"^login/$", auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    url(r"^logout/$", auth_views.logout_then_login, name="logout"),
    # Auth
    url(r"api/auth/", include("knox.urls")),
    # Iconify SVG icons
    url(r"icons/", include("dj_iconify.urls")),
    ## SODAR Core
    # Projectroles URLs
    url(r"^project/", include("projectroles.urls")),
    # Filesfolders URLs
    url(r"^filesfolders/", include("filesfolders.urls")),
    # django-db-file-storage URLs (needed for admin, obfuscated for users)
    url(r"^xu7in5zs9lylar0n/", include("db_file_storage.urls")),
    # Timeline URLs
    url(r"^timeline/", include("timeline.urls")),
    # User Profile URLs
    url(r"^user/", include("userprofile.urls")),
    # Admin Alerts URLs
    url(r"^alerts/", include("adminalerts.urls")),
    # Background jobs URLs
    url(r"^bgjobs/", include("bgjobs.urls")),
    # Site Info URLs
    url(r"^siteinfo/", include("siteinfo.urls")),
    # API Tokens URLs
    url(r"^tokens/", include("tokens.urls")),
    ## Local Apps
    url(r"^sequencers/", include("sequencers.urls")),
    url(r"^barcodes/", include("barcodes.urls")),
    url(r"^flowcells/", include("flowcells.urls")),
    ## Local Apps API
    url(r"^api/", include("digestiflow.api_urls")),
    # The rendered Sphinx-based manual.
    url(r"^manual/", include("docs.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.FILEBOXES_ENABLED:
    urlpatterns += [
        url(r"fileboxes/", include("fileboxes.urls")),
    ]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r"^400/$", default_views.bad_request, kwargs={"exception": Exception("Bad Request!")}),
        url(
            r"^403/$",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        url(
            r"^404/$",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        url(r"^500/$", default_views.server_error),
    ]

    urlpatterns += staticfiles_urlpatterns()

    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [url(r"^__debug__/", include(debug_toolbar.urls))] + urlpatterns

sequencers/urls.py
from django.conf.urls import url
from . import views

app_name = "sequencers"

urlpatterns = [
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/sequencer/$",
        view=views.SequencingMachineListView.as_view(),
        name="sequencer-list",
    ),
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/sequencer/create$",
        view=views.SequencingMachineCreateView.as_view(),
        name="sequencer-create",
    ),
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/sequencer/(?P<sequencer>[0-9a-f-]+)/$",
        view=views.SequencingMachineDetailView.as_view(),
        name="sequencer-detail",
    ),
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/sequencer/(?P<sequencer>[0-9a-f-]+)/update$",
        view=views.SequencingMachineUpdateView.as_view(),
        name="sequencer-update",
    ),
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/sequencer/(?P<sequencer>[0-9a-f-]+)/delete$",
        view=views.SequencingMachineDeleteView.as_view(),
        name="sequencer-delete",
    ),
]

flowcells/models.py
import re
import uuid as uuid_object

from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.postgres.fields import ArrayField
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models, transaction
from django.db.models import JSONField, Q
from django.urls import reverse

from mail_factory import factory
import pagerange
from projectroles.models import Project, PROJECT_TAG_STARRED
from filesfolders.models import Folder

from . import bases_mask
from digestiflow.users.models import User
from digestiflow.utils import revcomp
from barcodes.models import BarcodeSetEntry
from sequencers.models import SequencingMachine, INDEX_WORKFLOW_B


# Access Django user model
AUTH_USER_MODEL = getattr(settings, "AUTH_USER_MODEL", "auth.User")

#: Threshold on read fraction showing an index to ignore if found in index histogram but not in library.
THRESH_MIN_INDEX_FRAC = 0.01


def pretty_range(value):
    return pagerange.PageRange(value).range


def prefix_match(query, db):
    """Naive implementation of "is seq prefix of one in expecteds or vice versa"."""
    for entry in db:
        min_len = min(len(query), len(entry))
        if query[:min_len] == entry[:min_len]:
            return True
    return False


#: Status for "initial"/"not started", not automatically started yet for conversion.
STATUS_INITIAL = "initial"

#: Status for "ready to start"
STATUS_READY = "ready"

#: Status for "in progress"
STATUS_IN_PROGRESS = "in_progress"

#: Status for "complete" (automatic)
STATUS_COMPLETE = "complete"

#: Status for "complete_warnings" (manual)
STATUS_COMPLETE_WARNINGS = "complete_warnings"

#: Status for "failed" (automatic)
STATUS_FAILED = "failed"

#: Status for closed/released/receival confirmed (by user)
STATUS_CLOSED = "closed"

#: Status for confirmed failed/confirmed canceled (by user)
STATUS_CANCELED = "canceled"

#: Status for "skipped" (only used for conversion)
STATUS_SKIPPED = "skipped"

#: Statuses for sequencing
SEQUENCING_STATUS_CHOICES = (
    (STATUS_INITIAL, "not started"),
    (STATUS_IN_PROGRESS, "in progress"),
    (STATUS_COMPLETE, "complete"),
    (STATUS_COMPLETE_WARNINGS, "complete with warnings"),
    (STATUS_CLOSED, "released"),
    (STATUS_FAILED, "failed"),
    (STATUS_CANCELED, "failured confirmed"),
)

#: Statuses for base call to sequence conversion
CONVERSION_STATUS_CHOICES = (
    (STATUS_INITIAL, "keep unstarted"),
    (STATUS_READY, "ready to start"),
    (STATUS_IN_PROGRESS, "in progress"),
    (STATUS_COMPLETE, "complete"),
    (STATUS_COMPLETE_WARNINGS, "complete with warnings"),
    (STATUS_FAILED, "failed"),
    (STATUS_CLOSED, "released"),
    (STATUS_CANCELED, "failured confirmed"),
    (STATUS_SKIPPED, "skipped"),
)

#: Statuses for delivery
DELIVERY_STATUS_CHOICES = (
    (STATUS_INITIAL, "not started"),
    (STATUS_IN_PROGRESS, "in progress"),
    (STATUS_COMPLETE, "complete"),
    (STATUS_COMPLETE_WARNINGS, "complete with warnings"),
    (STATUS_CLOSED, "received"),
    (STATUS_FAILED, "canceled"),
    (STATUS_CANCELED, "canceled confirmed"),
    (STATUS_SKIPPED, "skipped"),
)

#: Delivery of sequences (FASTQ)
DELIVERY_TYPE_SEQ = "seq"

#: Delivery of base calls (BCL)
DELIVERY_TYPE_BCL = "bcl"

#: Delivery of both sequences and base calls
DELIVERY_TYPE_BOTH = "seq_bcl"

#: Delivery options
DELIVERY_CHOICES = (
    (DELIVERY_TYPE_SEQ, "sequences"),
    (DELIVERY_TYPE_BCL, "base calls"),
    (DELIVERY_TYPE_BOTH, "sequences + base calls"),
)


#: RTA version key for v1
RTA_VERSION_V1 = 1

#: RTA version key for v2
RTA_VERSION_V2 = 2

#: RTA version key for v2
RTA_VERSION_V3 = 3

#: RTA version key for 'other'
RTA_VERSION_OTHER = 0

#: RTA version used for a flow cell
RTA_VERSION_CHOICES = (
    #: RTA v1.x, old bcl2fastq required
    (RTA_VERSION_V1, "RTA v1"),
    #: RTA v2.x, bcl2fast2 required
    (RTA_VERSION_V2, "RTA v2"),
    #: RTA v3.x, bcl2fast2 required
    (RTA_VERSION_V3, "RTA v3"),
    #: other, for future-proofness
    (RTA_VERSION_OTHER, "other"),
)


#: Current version of error cache computation code.
FLOWCELL_ERROR_CACHE_VERSION = 3


class FlowCellManager(models.Manager):
    """Manager for custom table-level SequencingMachine queries"""

    def find(self, search_terms, keywords=None):
        """
        Return FlowCell objects matching the query.

        :param search_terms: Search terms (list of strings)
        :param keywords: Optional search keywords as key/value pairs (dict)
        :return: QuerySet of FlowCell objects
        """
        objects = super().get_queryset()
        query = Q()
        for t in search_terms:
            query = (
                query
                | Q(vendor_id__icontains=t)
                | Q(label__icontains=t)
                | Q(manual_label__icontains=t)
                | Q(description__icontains=t)
            )
        return objects.filter(query)


def validate_bases_mask(value):
    """Django validator for bases mask values."""
    if value:
        try:
            bases_mask.split_bases_mask(value)
        except bases_mask.BaseMaskConfigException as e:
            raise ValidationError(str(e)) from e


class FlowCell(models.Model):
    """Information stored for each flow cell"""

    #: DateTime of creation
    date_created = models.DateTimeField(auto_now_add=True, help_text="DateTime of creation")

    #: DateTime of last modification
    date_modified = models.DateTimeField(auto_now=True, help_text="DateTime of last modification")

    #: UUID used for identification throughout SODAR.
    sodar_uuid = models.UUIDField(
        default=uuid_object.uuid4, unique=True, help_text="Barcodeset SODAR UUID"
    )

    #: The project containing this barcode set.
    project = models.ForeignKey(
        Project, help_text="Project in which this flow cell belongs", on_delete=models.CASCADE
    )

    #: Run date of the flow cell
    run_date = models.DateField()

    #: The sequencer used for processing this flow cell
    sequencing_machine = models.ForeignKey(SequencingMachine, null=False, on_delete=models.PROTECT)

    #: The run number on the machine
    run_number = models.PositiveIntegerField()

    #: The slot of the machine
    slot = models.CharField(max_length=1)

    #: The vendor ID of the flow cell name
    vendor_id = models.CharField(max_length=40)

    #: The label of the flow cell
    label = models.CharField(blank=True, null=True, max_length=100)

    #: Manual override for the flow cell label.
    manual_label = models.CharField(
        blank=True,
        null=True,
        max_length=100,
        help_text="Manual label for overriding the one from the folder name",
    )

    #: Short description length
    description = models.TextField(
        blank=True, null=True, help_text="Short description of the flow cell"
    )

    #: Number of lanes on the flow cell
    num_lanes = models.IntegerField(
        blank=False,
        null=False,
        default=8,
        help_text="Number of lanes on flowcell 8 for HiSeq, 4 for NextSeq",
    )

    #: Name of the sequencing machine operator
    operator = models.CharField(
        blank=True, null=True, max_length=100, verbose_name="Sequencer Operator"
    )

    #: The user responsible for demultiplexing
    demux_operator = models.ForeignKey(
        User,
        blank=True,
        null=True,
        verbose_name="Demultiplexing Operator",
        related_name="demuxed_flowcells",
        on_delete=models.SET_NULL,
        help_text="User responsible for demultiplexing",
    )

    #: RTA version used, required for picking BCL to FASTQ and demultiplexing software
    rta_version = models.IntegerField(
        blank=False,
        null=False,
        default=RTA_VERSION_V2,
        choices=RTA_VERSION_CHOICES,
        help_text="Major RTA version, implies bcl2fastq version",
    )

    #: Status of sequencing
    status_sequencing = models.CharField(
        blank=False,
        null=False,
        max_length=50,
        default=STATUS_INITIAL,
        choices=SEQUENCING_STATUS_CHOICES,
        help_text="Choices for sequencing",
    )

    #: Status of base call to sequence conversion
    status_conversion = models.CharField(
        blank=False,
        null=False,
        max_length=50,
        default=STATUS_INITIAL,
        choices=CONVERSION_STATUS_CHOICES,
        help_text="Choices for sequencing",
    )

    #: Status of data delivery
    status_delivery = models.CharField(
        blank=False,
        null=False,
        max_length=50,
        default=STATUS_INITIAL,
        choices=DELIVERY_STATUS_CHOICES,
        help_text="Choices for sequencing",
    )

    #: What to deliver: sequences, base calls, or both.
    delivery_type = models.CharField(
        blank=False,
        null=False,
        max_length=50,
        default=DELIVERY_TYPE_SEQ,
        choices=DELIVERY_CHOICES,
        help_text="Choices for data delivery type",
    )

    #: Information about the planned read in Picard notation, that is B for Sample Barcode, M for molecular barcode,
    #: T for Template, and S for skip.
    planned_reads = models.CharField(
        max_length=200,
        blank=True,
        null=True,
        validators=[validate_bases_mask],
        help_text="Specification of the planned reads",
    )

    #: Information about the currently performed reads in Picard notation.
    current_reads = models.CharField(
        max_length=200,
        blank=True,
        null=True,
        validators=[validate_bases_mask],
        help_text="Specification of the current reads",
    )

    #: Optional override for reads information to override ``planned_reads`` in demultiplexing (in Picard notation)
    demux_reads = models.CharField(
        max_length=200,
        blank=True,
        null=True,
        validators=[validate_bases_mask],
        help_text="Specification of the reads to use for demultiplexing (defaults to planned reads)",

sequencers/forms.py
"""Forms for the sequencers app."""

from django import forms

from digestiflow.utils import HorizontalFormHelper
from .models import SequencingMachine


class SequencingMachineForm(forms.ModelForm):
    """Form for creating and updating ``SequencingMachine`` records."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Setup crispy-forms helper
        self.helper = HorizontalFormHelper()

    class Meta:
        model = SequencingMachine
        fields = (
            "vendor_id",
            "label",
            "description",
            "machine_model",
            "slot_count",
            "dual_index_workflow",
        )
        widgets = {"description": forms.Textarea(attrs={"rows": 3})}

sequencers/api/views.py
"""API Views for the ``sequencers`` app."""

from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView, RetrieveAPIView

from digestiflow.utils import ProjectMixin, SodarObjectInProjectPermissions
from ..models import SequencingMachine
from .serializers import SequencingMachineSerializer


class SequencingMachineApiViewMixin(ProjectMixin):
    """Common behaviour of FlowCell API views."""

    def get_serializer_context(self):
        result = super().get_serializer_context()
        result["project"] = self.get_project()
        return result

    def get_queryset(self):
        return SequencingMachine.objects.filter(project=self.get_project())


class SequencingMachineCreateApiView(SequencingMachineApiViewMixin, ListCreateAPIView):
    queryset = SequencingMachine.objects.all()
    permission_classes = (SodarObjectInProjectPermissions,)
    serializer_class = SequencingMachineSerializer
    lookup_url_kwarg = "sequencer"
    lookup_field = "sodar_uuid"


class SequencingMachineUpdateDestroyApiView(
    SequencingMachineApiViewMixin, RetrieveUpdateDestroyAPIView
):
    queryset = SequencingMachine.objects.all()
    permission_classes = (SodarObjectInProjectPermissions,)
    serializer_class = SequencingMachineSerializer
    lookup_url_kwarg = "sequencer"
    lookup_field = "sodar_uuid"


class SequencingMachineByVendorApiView(SequencingMachineApiViewMixin, RetrieveAPIView):
    queryset = SequencingMachine.objects.all()
    permission_classes = (SodarObjectInProjectPermissions,)
    serializer_class = SequencingMachineSerializer
    lookup_url_kwarg = "sequencer"
    lookup_field = "vendor_id"

sequencers/templates/sequencers/_sequencer_create_update.html
{% extends "projectroles/base.html" %}

{% load crispy_forms_tags %}

{% block navi_sub_project_extend %}
  <li class="breadcrumb-item">
    <a href="{% url 'sequencers:sequencer-list' project=project.sodar_uuid %}">Sequencers</a>
  </li>
  {% if object.pk %}
    <li class="breadcrumb-item">
      <a href="{% url 'sequencers:sequencer-detail' project=project.sodar_uuid sequencer=object.sodar_uuid %}">
        {{ object.vendor_id }} ({{ object.label }})
      </a>
    </li>
    <li class="breadcrumb-item active">
      Update
    </li>
  {% else %}
    <li class="breadcrumb-item active">
      Create
    </li>
  {% endif %}
{% endblock %}

{% block title %}
  {% if object.pk %}
    Updating {{ object.vendor_id }} ({{ vendor.label }})
  {% else %}
    Create new Sequencer in {{ project.title }}
  {% endif %}
{% endblock title %}

{% block projectroles %}
  <div class="row sodar-pr-content-title pb-2">
    {# Project menu dropdown, only visible if browser width < X and sidebar is hidden #}
    {% include 'projectroles/_project_menu_btn.html' %}

    <h2 class="sodar-pr-content-title">
      {% if object.pk %}
        Update
      {% else %}
        Create
      {% endif %}
      Sequencing Machine
    </h2>
  </div>

  <div class="container-fluid sodar-page-container">
    <form method="post">
      {% if object.pk %}
        <div class="form-group row">
          <label class="form-control-label {{ form.helper.label_class }}">UUID</label>
          <div class="{{ form.helper.field_class}}">
            <input type="text" readonly class="form-control-plaintext" value="{{ object.sodar_uuid }}">
          </div>
        </div>
        <div class="form-group row">
          <label class="form-control-label {{ form.helper.label_class }}">Project</label>
          <div class="{{ form.helper.field_class}}">
            <input type="text" readonly class="form-control-plaintext" value="{{ object.project.title }}">
          </div>
        </div>
        <div class="form-group row">
          <label class="form-control-label {{ form.helper.label_class }}">Created</label>
          <div class="{{ form.helper.field_class}}">
            <input type="text" readonly class="form-control-plaintext" value="{{ object.date_created }}">
          </div>
        </div>
        <div class="form-group row">
          <label class="form-control-label {{ form.helper.label_class }}">Last Update</label>
          <div class="{{ form.helper.field_class}}">
            <input type="text" readonly class="form-control-plaintext" value="{{ object.date_modified }}">
          </div>
        </div>
      {% endif %}

      {% crispy form form.helper %}

      <div class="text-right mb-3">
        <div class="btn-group" role="group">
          <a role="button" class="btn btn-secondary"
            {% if object.pk %}
              href="{% url 'sequencers:sequencer-detail' project=project.sodar_uuid sequencer=object.sodar_uuid %}">
            {% else %}
              href="{% url 'sequencers:sequencer-list' project=project.sodar_uuid %}">
            {% endif %}
            <i class="iconify" data-icon="mdi:arrow-left-circle"></i>
            Cancel
          </a>
          <button type="submit" class="btn btn-primary">
            <i class="iconify" data-icon="mdi:check-bold"></i>
            {% if object.pk %}
              Update
            {% else %}
              Create
            {% endif %}
          </button>
        </div>
      </div>
    </form>
  </div>

{% endblock %}

sequencers/templates/sequencers/_sequencer_detail_buttons.html
<div class="btn-group ml-auto" id="sodar-ff-buttons-list">
  <button class="btn btn-primary dropdown-toggle"
          type="button" data-toggle="dropdown"
          aria-haspopup="true" aria-expanded="false">
    Sequencer Operations
  </button>
  <div class="dropdown-menu dropdown-menu-right">
    <a class="dropdown-item" href="{% url 'sequencers:sequencer-create' project=project.sodar_uuid %}">
      <i class="iconify" data-icon="mdi:plus-thick"></i> Create
    </a>
    <a class="dropdown-item" href="{% url 'sequencers:sequencer-update' project=project.sodar_uuid sequencer=object.sodar_uuid %}">
      <i class="iconify" data-icon="mdi:lead-pencil"></i> Update
    </a>
    <a class="dropdown-item" href="{% url 'sequencers:sequencer-delete' project=project.sodar_uuid sequencer=object.sodar_uuid %}">
      <i class="iconify" data-icon="mdi:close-thick"></i> Delete
    </a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="{% url 'api:sequencers' project=project.sodar_uuid sequencer=object.sodar_uuid %}?format=json">
      <i class="iconify" data-icon="mdi:cloud-download"></i> JSON Export
    </a>
  </div>
</div>

sequencers/templates/sequencers/_sequencer_flowcells.html
<p>
  <em>
    <i class="iconify" data-icon="mdi:information"></i>
    The following flow cells/runs are known for this sequencer.
  </em>
</p>

{% include "flowcells/_flowcell_table.html" with object_list=object.flowcell_set.all %}

sequencers/templates/sequencers/_sequencer_item.html
<tr>
  <td class="text-right text-muted">{{ forloop.counter }}</td>
  <td class="text-nowrap">{{ item.date_created|date:"Y/m/d H:i" }}</td>
  <td>
    <a href="{{ item.get_absolute_url }}">
      {{ item.vendor_id }}
    </a>
  </td>
  <td>
    {{ item.label }}
  </td>
  <td class="text-right">
    {{ item.flowcell_set.count }}
  </td>
  <td>
    {{ item.description|default:"-" }}
    {% if not details_card_mode %}
      {% include "sequencers/_sequencer_item_buttons.html" %}
    {% endif %}
  </td>
</tr>

sequencers/templates/sequencers/_sequencer_item_buttons.html
<div class="btn-group sodar-list-btn-group pull-right">
  <button class="btn btn-secondary dropdown-toggle sodar-list-dropdown"
      type="button" data-toggle="dropdown" aria-expanded="false">
    <i class="iconify" data-icon="mdi:cog"></i>
  </button>
  <div class="dropdown-menu dropdown-menu-right">
    <a class="dropdown-item" href="{% url 'sequencers:sequencer-update' project=project.sodar_uuid sequencer=item.sodar_uuid %}">
      <i class="iconify" data-icon="mdi:lead-pencil"></i>
      Update
    </a>
    <a class="dropdown-item" href="{% url 'sequencers:sequencer-delete' project=project.sodar_uuid sequencer=item.sodar_uuid %}">
      <i class="iconify" data-icon="mdi:close-thick"></i>
      Delete
    </a>
  </div>
</div>

sequencers/templates/sequencers/sequencer_confirm_delete.html
{% extends "projectroles/base.html" %}

{% block navi_sub_project_extend %}
  <li class="breadcrumb-item">
    <a href="{% url 'sequencers:sequencer-list' project=project.sodar_uuid %}">Sequencers</a>
  </li>
  <li class="breadcrumb-item">
    <a href="{% url 'sequencers:sequencer-detail' project=project.sodar_uuid sequencer=object.sodar_uuid %}">
        {{ object.vendor_id }}
    </a>
  </li>
  <li class="breadcrumb-item active">Delete</li>
{% endblock %}

{% block title %}
  Confirm Removal of Sequencing Machine {{ object.vendor_id }} ({{ object.label }})
{% endblock title %}

{% block projectroles %}
  <div class="row sodar-pr-content-title pb-2">
    {# Project menu dropdown, only visible if browser width < X and sidebar is hidden #}
    {% include 'projectroles/_project_menu_btn.html' %}

    <h2 class="sodar-pr-content-title">
      Really Delete Sequencer &quot;{{ object.vendor_id }}&quot;?
    </h2>
  </div>

  <div class="container-fluid sodar-page-container">

    {% include "sequencers/_sequencer_properties.html" %}

    <form method="post">
      {% csrf_token %}
      <div class="btn-group pull-right">
        <a role="button" class="btn btn-secondary"
            href="{{ request.session.real_referer }}">
          <i class="iconify" data-icon="mdi:arrow-left-circle"></i> Cancel
        </a>
        <button type="submit" class="btn btn-danger">
          <i class="iconify" data-icon="mdi:close-thick"></i> Remove
        </button>
      </div>
    </form>
  </div>

{% endblock %}

sequencers/templates/sequencers/sequencer_create.html
{% include "sequencers/_sequencer_create_update.html" %}

sequencers/templates/sequencers/sequencer_detail.html
{% extends "projectroles/project_base.html" %}

{% block navi_sub_project_extend %}
  <li class="breadcrumb-item">
    <a href="{% url 'sequencers:sequencer-list' project=project.sodar_uuid %}">Sequencers</a>
  </li>
    <li class="breadcrumb-item active">
      {{ object.vendor_id }} ({{ object.label }})
  </li>
{% endblock %}

{% block projectroles %}
  <div class="row sodar-pr-content-title pb-2">
    {# Project menu dropdown, only visible if browser width < X and sidebar is hidden #}
    {% include 'projectroles/_project_menu_btn.html' %}

    <h2 class="sodar-pr-content-title">
      Sequencing Machine &quot;{{ object.vendor_id }}&quot; ({{ object.label }})
    </h2>
    {% include "sequencers/_sequencer_detail_buttons.html" %}
  </div>

  <div class="container-fluid sodar-page-container">
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a class="nav-link active" id="properties-tab" data-toggle="tab" href="#properties" aria-controls="properties" aria-selected="true">Properties</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="flowcells-tab" data-toggle="tab" href="#flowcells" aria-controls="flowcells" aria-selected="true">
          Flow Cells/Runs
          <span class="badge badge-secondary ml-1">{{ object.flowcell_set.count }}</span>
        </a>
      </li>
    </ul>

    <div class="tab-content border-left border-right border-bottom" id="flowcellTabContent">
      <div class="tab-pane show active" id="properties" role="tabpanel" aria-labelledby="properties-tab">
        <div class="row py-3">
          <div class="col">
            {% include "sequencers/_sequencer_properties.html" %}
          </div>
        </div>
      </div>
      <div class="tab-pane face" id="flowcells" role="tabpanel" aria-labelledby="flowcells-tab">
        <div class="row py-3">
          <div class="col">
            {% include "sequencers/_sequencer_flowcells.html" %}
          </div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

sequencers/templates/sequencers/sequencer_update.html
{% include "sequencers/_sequencer_create_update.html" %}