config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.shortcuts import render
from django.views import defaults as default_views
from django.views.generic import TemplateView

from projectroles.views import HomeView
from sentry_sdk import last_event_id


def handler500(request, *args, **argv):
    return render(request, "500.html", {"sentry_event_id": last_event_id()}, status=500)


urlpatterns = [
    url(r"^$", HomeView.as_view(), name="home"),
    url(r"^about/$", TemplateView.as_view(template_name="pages/about.html"), name="about"),
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),
    # Login and logout
    url(r"^login/$", auth_views.LoginView.as_view(template_name="users/login.html"), name="login"),
    url(r"^logout/$", auth_views.logout_then_login, name="logout"),
    # Auth
    url(r"api/auth/", include("knox.urls")),
    # Iconify SVG icons
    url(r"icons/", include("dj_iconify.urls")),
    ## SODAR Core
    # Projectroles URLs
    url(r"^project/", include("projectroles.urls")),
    # Filesfolders URLs
    url(r"^filesfolders/", include("filesfolders.urls")),
    # django-db-file-storage URLs (needed for admin, obfuscated for users)
    url(r"^xu7in5zs9lylar0n/", include("db_file_storage.urls")),
    # Timeline URLs
    url(r"^timeline/", include("timeline.urls")),
    # User Profile URLs
    url(r"^user/", include("userprofile.urls")),
    # Admin Alerts URLs
    url(r"^alerts/", include("adminalerts.urls")),
    # Background jobs URLs
    url(r"^bgjobs/", include("bgjobs.urls")),
    # Site Info URLs
    url(r"^siteinfo/", include("siteinfo.urls")),
    # API Tokens URLs
    url(r"^tokens/", include("tokens.urls")),
    ## Local Apps
    url(r"^sequencers/", include("sequencers.urls")),
    url(r"^barcodes/", include("barcodes.urls")),
    url(r"^flowcells/", include("flowcells.urls")),
    ## Local Apps API
    url(r"^api/", include("digestiflow.api_urls")),
    # The rendered Sphinx-based manual.
    url(r"^manual/", include("docs.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.FILEBOXES_ENABLED:
    urlpatterns += [
        url(r"fileboxes/", include("fileboxes.urls")),
    ]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r"^400/$", default_views.bad_request, kwargs={"exception": Exception("Bad Request!")}),
        url(
            r"^403/$",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        url(
            r"^404/$",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        url(r"^500/$", default_views.server_error),
    ]

    urlpatterns += staticfiles_urlpatterns()

    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [url(r"^__debug__/", include(debug_toolbar.urls))] + urlpatterns

fileboxes/urls.py
from django.conf.urls import url
from . import views

app_name = "fileboxes"

urlpatterns = [
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/filebox/$",
        view=views.FileBoxListView.as_view(),
        name="filebox-list",
    ),
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/filebox/create$",
        view=views.FileBoxCreateView.as_view(),
        name="filebox-create",
    ),
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/filebox/(?P<filebox>[0-9a-f-]+)/$",
        view=views.FileBoxDetailView.as_view(),
        name="filebox-detail",
    ),
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/filebox/(?P<filebox>[0-9a-f-]+)/update/$",
        view=views.FileBoxUpdateView.as_view(),
        name="filebox-update",
    ),
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/filebox/(?P<filebox>[0-9a-f-]+)/delete/$",
        view=views.FileBoxDeleteView.as_view(),
        name="filebox-delete",
    ),
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/filebox/(?P<filebox>[0-9a-f-]+)/grant/$",
        view=views.FileBoxGrantView.as_view(),
        name="filebox-grant",
    ),
    url(
        regex=r"^(?P<project>[0-9a-f-]+)/filebox/(?P<filebox>[0-9a-f-]+)/revoke/$",
        view=views.FileBoxRevokeView.as_view(),
        name="filebox-revoke",
    ),
]

fileboxes/forms.py
"""Forms for the fileboxes app."""

from django import forms

from digestiflow.utils import HorizontalFormHelper
from .models import FileBox


class FileBoxForm(forms.ModelForm):
    """Form for creating and updating ``FileBox`` records."""

    def __init__(self, *args, **kwargs):
        self.project = kwargs.pop("project")
        super().__init__(*args, **kwargs)
        # Setup crispy-forms helper
        self.helper = HorizontalFormHelper()

    class Meta:
        model = FileBox
        fields = ("title", "description", "state_meta", "date_frozen", "date_expiry")
        widgets = {"description": forms.Textarea(attrs={"rows": 3})}


class FileBoxGrantForm(forms.Form):
    """Form for granting access to projects"""

    users = forms.CharField(
        min_length=3,
        label="Account(s)",
        help_text="Account names or email addresses of users to grant access.",
    )

    def __init__(self, *args, **kwargs):
        if "instance" in kwargs:
            self.instance = kwargs.pop("instance")
        super().__init__(*args, **kwargs)
        # Setup crispy-forms helper
        self.helper = HorizontalFormHelper()


class FileBoxRevokeForm(forms.Form):
    """Form for revoking access from projects."""

    def __init__(self, *args, **kwargs):
        if "instance" in kwargs:
            self.instance = kwargs.pop("instance")
        super().__init__(*args, **kwargs)

fileboxes/api/views.py
"""API Views for the flowcells app."""

from projectroles.views_api import SODARAPIBaseProjectMixin
from rest_framework.generics import ListCreateAPIView, RetrieveUpdateAPIView

from .serializers import FileBoxSerializer, FileBoxAuditEntrySerializer
from ..models import FileBox, FileBoxAuditEntry


class FileBoxListCreateApiView(SODARAPIBaseProjectMixin, ListCreateAPIView):
    permission_required = "fileboxes.view_data"
    serializer_class = FileBoxSerializer

    def get_queryset(self):
        return FileBox.objects.filter(project=self.get_project()).prefetch_related("account_grants")


class FileBoxRetrieveUpdateApiView(SODARAPIBaseProjectMixin, RetrieveUpdateAPIView):
    permission_required = "fileboxes.view_data"
    serializer_class = FileBoxSerializer

    lookup_url_kwarg = "filebox"
    lookup_field = "sodar_uuid"

    def get_queryset(self):
        return FileBox.objects.filter(project=self.get_project()).prefetch_related("account_grants")


class FileBoxAuditEntryListCreateApiView(SODARAPIBaseProjectMixin, ListCreateAPIView):
    permission_required = "fileboxes.view_data"
    serializer_class = FileBoxAuditEntrySerializer

    def get_serializer_context(self):
        result = super().get_serializer_context()
        result["file_box"] = self.get_filebox()
        return result

    def get_filebox(self):
        return FileBox.objects.get(
            project=self.get_project(), sodar_uuid=self.kwargs.get("filebox")
        )

    def get_queryset(self):
        return FileBoxAuditEntry.objects.filter(file_box=self.get_filebox())

fileboxes/views.py
"""The views for the fileboxes app."""

import re

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.db import transaction
from django.db.models import Q
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import CreateView, DeleteView, DetailView, ListView, UpdateView
from projectroles.plugins import get_backend_api
from projectroles.views import LoggedInPermissionMixin, ProjectContextMixin, ProjectPermissionMixin

from .forms import FileBoxForm, FileBoxGrantForm, FileBoxRevokeForm
from .models import FileBox


class FileBoxListView(
    LoginRequiredMixin,
    LoggedInPermissionMixin,
    ProjectPermissionMixin,
    ProjectContextMixin,
    ListView,
):
    """Display list of all FileBox records"""

    template_name = "fileboxes/filebox_list.html"
    permission_required = "fileboxes.view_data"

    model = FileBox
    paginate_by = 20

    def get_queryset(self):
        return super().get_queryset().filter(project__sodar_uuid=self.kwargs["project"])


class FileBoxDetailView(
    LoginRequiredMixin,
    LoggedInPermissionMixin,
    ProjectPermissionMixin,
    ProjectContextMixin,
    DetailView,
):
    """Display detail of FileBox records"""

    template_name = "fileboxes/filebox_detail.html"
    permission_required = "fileboxes.view_data"

    model = FileBox

    slug_url_kwarg = "filebox"
    slug_field = "sodar_uuid"

    def get_context_data(self, *args, **kwargs):
        result = super().get_context_data(*args, **kwargs)
        result["grant_form"] = FileBoxGrantForm()
        return result


class FileBoxCreateView(
    SuccessMessageMixin,
    LoginRequiredMixin,
    LoggedInPermissionMixin,
    ProjectPermissionMixin,
    ProjectContextMixin,
    CreateView,
):
    """Display list of all FileBox records"""

    success_message = "File box successfully created."
    template_name = "fileboxes/filebox_create.html"
    permission_required = "fileboxes.add_data"

    model = FileBox
    form_class = FileBoxForm

    def get_form_kwargs(self, *args, **kwargs):
        result = super().get_form_kwargs(*args, **kwargs)
        result.setdefault("project", self.get_project())
        return result

    @transaction.atomic
    def form_valid(self, form):
        """Automatically set the project property."""
        # Create the sequencing machine.
        form.instance.project = self.get_project(self.request, self.kwargs)
        result = super().form_valid(form)
        # Add audit trail event.
        form.instance.audit_entries.create(
            actor=self.request.user,
            action="CREATE",
            message="created new file box '%s'" % form.instance.title,
        )
        # Register event with timeline.
        timeline = get_backend_api("timeline_backend")
        if timeline:
            tl_event = timeline.add_event(
                project=self.get_project(self.request, self.kwargs),
                app_name="fileboxes",
                user=self.request.user,
                event_name="filebox_create",
                description="create filebox {filebox}",
                status_type="OK",
            )
            tl_event.add_object(obj=self.object, label="filebox", name=self.object.title)
        return result


class FileBoxUpdateView(
    SuccessMessageMixin,
    LoginRequiredMixin,
    LoggedInPermissionMixin,
    ProjectPermissionMixin,
    ProjectContextMixin,
    UpdateView,
):
    """Updating of FileBox records"""

    success_message = "File box successfully updated."
    template_name = "fileboxes/filebox_update.html"
    permission_required = "fileboxes.change_data"

    model = FileBox
    form_class = FileBoxForm

    slug_url_kwarg = "filebox"
    slug_field = "sodar_uuid"

    def form_valid(self, form):
        with transaction.atomic():
            old_object = FileBox.objects.get(id=self.object.id)
            if getattr(old_object, "state_meta") != form.cleaned_data["state_meta"]:
                self._register_state_change(
                    "state_meta", getattr(old_object, "state_meta"), form.cleaned_data["state_meta"]
                )
            changed = []
            for field in ("title", "description", "date_frozen", "date_expiry"):
                if getattr(old_object, field) != form.cleaned_data[field]:
                    changed.append((field, getattr(old_object, field), form.cleaned_data[field]))
            if changed:
                self._register_attr_changes(changed)
        return super().form_valid(form)

    def _register_state_change(self, field, prv, nxt):
        old_object = FileBox.objects.get(id=self.object.id)
        old_object.update_state_meta(self.request.user, field, nxt)

    def _register_attr_changes(self, changes):
        # Add audit trail event.
        changes_str = ", ".join(
            ["'%s': '%s' -> '%s'" % tuple(map(str, change)) for change in changes]
        )
        self.object.audit_entries.create(
            actor=self.request.user,
            action="UPDATE_ATTRS",
            message="updated attributes of file box '%s': %s" % (self.object.title, changes_str),
        )
        # Register event with timeline.
        timeline = get_backend_api("timeline_backend")
        if timeline:
            tl_event = timeline.add_event(
                project=self.get_project(self.request, self.kwargs),
                app_name="fileboxes",
                user=self.request.user,
                event_name="filebox_update_attrs",
                description="updating attributes of file box {filebox}",
                status_type="OK",
            )
            tl_event.add_object(obj=self.object, label="filebox", name=self.object.title)

    def get_form_kwargs(self, *args, **kwargs):
        result = super().get_form_kwargs(*args, **kwargs)
        result.setdefault("project", self.get_project())
        return result


class FileBoxDeleteView(
    SuccessMessageMixin,
    LoginRequiredMixin,
    LoggedInPermissionMixin,
    ProjectPermissionMixin,
    ProjectContextMixin,
    DeleteView,
):
    """Deletion of FileBox records"""

    success_message = "File box successfully deactivated."
    template_name = "fileboxes/filebox_confirm_delete.html"
    permission_required = "fileboxes.delete_data"

    model = FileBox

    slug_url_kwarg = "filebox"
    slug_field = "sodar_uuid"

    @transaction.atomic
    def delete(self, *args, **kwargs):
        # Do not delete, just deactivate.
        self.object = self.get_object()
        if self.object.state_meta == "DELETED":
            return redirect(self.get_success_url())
        else:
            self.object.state_meta = "DELETED"
            self.object.save()
        # Add audit trail event.
        self.object.audit_entries.create(
            actor=self.request.user,
            action="UPDATE_STATE",
            message="deactivated file box '%s'" % self.object.title,
        )
        # Register event with timeline.
        timeline = get_backend_api("timeline_backend")
        if timeline:
            tl_event = timeline.add_event(
                project=self.get_project(self.request, self.kwargs),
                app_name="fileboxes",
                user=self.request.user,
                event_name="filebox_delete",
                description="deactivating file box {filebox}",
                status_type="OK",
            )
            tl_event.add_object(obj=self.object, label="filebox", name=self.object.title)
        return redirect(self.get_success_url())

    def get_success_url(self):
        return reverse(
            "fileboxes:filebox-list",
            kwargs={"project": self.get_project(self.request, self.kwargs).sodar_uuid},
        )


class FileBoxGrantView(
    SuccessMessageMixin,
    LoginRequiredMixin,
    LoggedInPermissionMixin,
    ProjectPermissionMixin,
    ProjectContextMixin,
    UpdateView,
):
    template_name = "fileboxes/filebox_detail.html"
    permission_required = "fileboxes.change_data"

    model = FileBox
    form_class = FileBoxGrantForm

    slug_url_kwarg = "filebox"
    slug_field = "sodar_uuid"

    def get_context_data(self, *args, **kwargs):
        result = super().get_context_data(*args, **kwargs)
        result["grant_form"] = result["form"]
        return result

    def _form_valid_ldap(self, accounts):
        """Handle valid form if LDAP is available"""
        preexisting_accounts = []
        created_accounts = []
        bad_accounts = []

        # import pdb; pdb.set_trace()

        ldap_conns = []
        if settings.ENABLE_LDAP:
            import ldap  # noqa

            ldap_conn = ldap.initialize(settings.AUTH_LDAP_SERVER_URI)
            ldap_conn.set_option(ldap.OPT_REFERRALS, ldap.OPT_OFF)
            ldap_conn.set_option(ldap.OPT_TIMEOUT, 5)
            ldap_conn.start_tls_s()
            ldap_conn.simple_bind_s(settings.AUTH_LDAP_BIND_DN, settings.AUTH_LDAP_BIND_PASSWORD)
            ldap_conns.append(
                (settings.AUTH_LDAP_USERNAME_DOMAIN, settings.AUTH_LDAP_USER_SEARCH_BASE, ldap_conn)
            )
        if settings.ENABLE_LDAP_SECONDARY:
            import ldap  # noqa

            ldap_conn = ldap.initialize(settings.AUTH_LDAP2_SERVER_URI)
            ldap_conn.set_option(ldap.OPT_REFERRALS, ldap.OPT_OFF)
            ldap_conn.set_option(ldap.OPT_TIMEOUT, 5)
            ldap_conn.start_tls_s()
            ldap_conn.simple_bind_s(settings.AUTH_LDAP2_BIND_DN, settings.AUTH_LDAP2_BIND_PASSWORD)
            ldap_conns.append(
                (
                    settings.AUTH_LDAP2_USERNAME_DOMAIN,
                    settings.AUTH_LDAP2_USER_SEARCH_BASE,
                    ldap_conn,
                )
            )

        with transaction.atomic():
            for account in accounts:
                for domain, search_base, conn in ldap_conns:

fileboxes/templates/fileboxes/_details_card.html
{% load fileboxes %}

<table class="table table-striped sodar-card-table">
  <thead>
    {% include 'fileboxes/_filebox_table_header.html' %}
  </thead>
  <tbody>
    {% get_details_fileboxes project as fileboxes %}
    {% if fileboxes.count > 0 %}
      {% for filebox in fileboxes %}
        {% include 'fileboxes/_filebox_item.html' with item=filebox details_card_mode=True %}
      {% endfor %}
    {% else %}
        <tr>
          <td class="bg-faded font-italic text-center" colspan="3">No file boxes (yet)</td>
        </tr>
    {% endif %}
  </tbody>
</table>

fileboxes/templates/fileboxes/_filebox_access.html
{% load crispy_forms_tags %}

<p>
  <em>
    <i class="iconify" data-icon="mdi:information"></i>
    The following accounts have been granted access to the data in the project.
  </em>
</p>

<div class="mb-5">
  <form method="post" action="{% url "fileboxes:filebox-grant" project=object.project.sodar_uuid filebox=object.sodar_uuid %}">
    {% crispy grant_form grant_form.helper %}
    <div class="text-right mb-3">
      <div class="btn-group" role="group">
        <button type="submit" class="btn btn-small btn-primary">
          <i class="iconify" data-icon="mdi:check-bold"></i>
          Search &amp; Grant Access
        </button>
      </div>
    </div>
  </form>
</div>

<table class="table table-striped table-hover table-sm popover-form-container">
  <thead>
    <tr>
      <th style="width: 100px;" class="text-center">Account</th>
      <th style="width: 200px;" class="text-center">Email</th>
      <th style="width: 200px;" class="text-center">Name</th>
      <th style="width: 0px;" class="text-right">Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for grant in object.account_grants.all %}
      <tr>
        <td>{{ grant.username }}</td>
        <td>{{ grant.email|default:"-" }}</td>
        <td>{{ grant.full_name|default:"-" }}</td>
        <td class="text-right">
          <div class="btn-group sodar-list-btn-group pull-right">
            <button class="btn btn-secondary dropdown-toggle sodar-list-dropdown"
                type="button" data-toggle="dropdown" aria-expanded="false">
              <i class="iconify" data-icon="mdi:cog"></i>
            </button>
            <div class="dropdown-menu dropdown-menu-right">
              <a class="dropdown-item" href="{% url 'fileboxes:filebox-revoke' project=project.sodar_uuid filebox=object.sodar_uuid %}?grant={{ grant.sodar_uuid }}">
                <i class="iconify" data-icon="mdi:cancel"></i>
                Revoke
              </a>
            </div>
          </div>
        </td>
      </tr>
    {% empty %}
      <tr>
        <td colspan="4" class="text-center font-italic">No users have been granted access (yet)</td>
      </tr>
    {% endfor %}
  </tbody>
</table>

fileboxes/templates/fileboxes/_filebox_audit.html
{% load humanize %}

<p>
  <em>
    <i class="iconify" data-icon="mdi:information"></i>
    Audit trail of this file box.
  </em>
</p>

<table class="table table-striped table-hover table-sm popover-form-container">
  <thead>
    <tr>
      <th style="width: 100px;" class="text-center">Date</th>
      <th style="width: 100px;" class="text-center">Actor</th>
      <th style="width: 100px;" class="text-center">Operation</th>
      <th class="text-center">Message</th>
    </tr>
  </thead>
  <tbody>
    {% for entry in object.audit_entries.all %}
      <tr>
        <td class="text-nowrap">
            <span data-toggle="tooltip" title="{{ message.date_created }}">
            {{ entry.date_created|naturaltime }}
          </span>
        </td>
        <td class="text-nowrap">
          {{ entry.actor.username }}
        </td>
        <td class="text-nowrap">
          {{ entry.action }}
        </td>
        <td class="text-nowrap">
          {{ entry.message }}
          {% if entry.raw_log %}
            <a onclick="javascript:$('#raw-log-{{ entry.sodar_uuid }}').toggle()"
              class="badge badge-light">
              <i class="iconify" data-icon="mdi:file-document-outline"></i> toggle log</a>
              <pre style="display: none;" id="raw-log-{{ entry.sodar_uuid }}">{{ entry.raw_log }}</pre>
          {% endif %}
        </td>
      </tr>
    {% endfor %}
  </tbody>
</table>

fileboxes/templates/fileboxes/_filebox_email.html
{% load projectroles_common_tags %}

{% get_django_setting 'FILEBOXES_BASE_URL' as filebox_base_url %}


<div class="row">
  <div class="col">
    <textarea class="form-control" rows="10">Dear Recipient,

I have created a shared folder on our file exchange server for us to exchange files. You can log in with your Charite (user@CHARITE) or MDC account (user@MDC-BERLIN) to access it.

{% if filebox_base_url %}The full URL of the shared folder is:

- {{  filebox_base_url }}/{{ object.sodar_uuid }}/
{% else %}The ID of the shared folder is:

- {{ object.sodar_uuid }}
{% endif %}
You can find out detailed instruction accessing the folder for different operating systems here:

- https://bihealth.github.io/bih-cluster/how-to/service/file-exchange/

Best wishes,
</textarea>
  </div>
</div>

fileboxes/templates/fileboxes/_filebox_item_buttons.html
<div class="btn-group sodar-list-btn-group pull-right">
  <button class="btn btn-secondary dropdown-toggle sodar-list-dropdown"
      type="button" data-toggle="dropdown" aria-expanded="false">
    <i class="iconify" data-icon="mdi:cog"></i>
  </button>
  <div class="dropdown-menu dropdown-menu-right">
    <a class="dropdown-item" href="{% url 'fileboxes:filebox-update' project=project.sodar_uuid filebox=item.sodar_uuid %}">
      <i class="iconify" data-icon="mdi:lead-pencil"></i>
      Update
    </a>
    <a class="dropdown-item" href="{% url 'fileboxes:filebox-delete' project=project.sodar_uuid filebox=item.sodar_uuid %}">
      <i class="iconify" data-icon="mdi:close-thick"></i>
      Delete
    </a>
  </div>
</div>

fileboxes/templates/fileboxes/_search_item.html
{# Projectroles dependency #}
{% load projectroles_common_tags %}

<tr class="sodar-ff-search-item" id="sodar-ff-search-item-{{ item.sodar_uuid }}">
  {# Name & link column #}
  <td>
    <div class="sodar-overflow-container">
      <a href="{{ item.get_absolute_url }}">
        {% autoescape off %}
          {% highlight_search_term item.title search_term %}
        {% endautoescape %}
      </a>
    </div>
  </td>
  {# Type column #}
  <td>
    <div class="sodar-overflow-container">
      File Box
    </div>
  </td>
  {# Project column #}
  <td>
    <div class="sodar-overflow-container">
      <a href="{% url 'projectroles:detail' project=item.project.sodar_uuid %}">
        {% autoescape off %}
          {# NOTE: No highlight here as project is not searched for here #}
          {{ item.project.title }}
        {% endautoescape %}
      </a>
    </div>
  </td>
  {# Description #}
  <td class="sodar-overflow-container">
    {% autoescape off %}
      {% highlight_search_term item.description|default:"-" search_term %}
    {% endautoescape %}
  </td>
</tr>

fileboxes/templates/fileboxes/filebox_confirm_delete.html
{% extends "projectroles/base.html" %}

{% block navi_sub_project_extend %}
  <li class="breadcrumb-item">
    <a href="{% url 'fileboxes:filebox-list' project=project.sodar_uuid %}">File Boxes</a>
  </li>
  <li class="breadcrumb-item">
    <a href="{% url 'fileboxes:filebox-detail' project=project.sodar_uuid filebox=object.sodar_uuid %}">
      {{ object.title }}
    </a>
  </li>
  <li class="breadcrumb-item active">Delete</li>
{% endblock %}

{% block title %}
  Confirm Removal of File Box {{ object.title }}
{% endblock title %}

{% block projectroles %}
  <div class="row sodar-pr-content-title pb-2">
    {# Project menu dropdown, only visible if browser width < X and sidebar is hidden #}
    {% include 'projectroles/_project_menu_btn.html' %}

    <h2 class="sodar-pr-content-title">
      Really Delete File Box &quot;{{ object.title }}&quot;?
    </h2>
  </div>

  <div class="container-fluid sodar-page-container">

    {% include "fileboxes/_filebox_properties.html" %}

    <form method="post">
      {% csrf_token %}
      <div class="btn-group pull-right">
        <a role="button" class="btn btn-secondary"
            href="{{ request.session.real_referer }}">
          <i class="iconify" data-icon="mdi:arrow-left-circle"></i> Cancel
        </a>
        <button type="submit" class="btn btn-danger">
          <i class="iconify" data-icon="mdi:close-thick"></i> Remove
        </button>
      </div>
    </form>
  </div>

{% endblock %}

fileboxes/templates/fileboxes/filebox_confirm_revoke.html
{% extends "projectroles/base.html" %}

{% block navi_sub_project_extend %}
  <li class="breadcrumb-item">
    <a href="{% url 'fileboxes:filebox-list' project=project.sodar_uuid %}">File Boxes</a>
  </li>
  <li class="breadcrumb-item">
    <a href="{% url 'fileboxes:filebox-detail' project=project.sodar_uuid filebox=object.sodar_uuid %}">
      {{ object.title }}
    </a>
  </li>
  <li class="breadcrumb-item active">Revoke Access</li>
{% endblock %}

{% block title %}
  Confirm Access Revokal for File Box {{ object.title }}
{% endblock title %}

{% block projectroles %}
  <div class="row sodar-pr-content-title pb-2">
    {# Project menu dropdown, only visible if browser width < X and sidebar is hidden #}
    {% include 'projectroles/_project_menu_btn.html' %}

    <h2 class="sodar-pr-content-title">
      Really Revoke Access to File Box &quot;{{ object.title }}&quot;?
    </h2>
  </div>

  <div class="container-fluid sodar-page-container">

    <p>
      The access for the account <span class="badge badge-warning">{{ grant.username }}</span> to file box {{ object.title }} will be marked for revokal.
      Do you want to continue?
    </p>

    <form method="post">
      {% csrf_token %}
      <div class="btn-group pull-right">
        <a role="button" class="btn btn-secondary"
            href="{{ request.session.real_referer }}">
          <i class="iconify" data-icon="mdi:arrow-left-circle"></i> Cancel
        </a>
        <button type="submit" class="btn btn-danger">
          <i class="iconify" data-icon="mdi:close-thick"></i> Revoke Access
        </button>
      </div>
    </form>
  </div>

{% endblock %}

fileboxes/templates/fileboxes/filebox_create.html
{% include "fileboxes/_filebox_create_update.html" %}

fileboxes/templates/fileboxes/filebox_update.html
{% include "fileboxes/_filebox_create_update.html" %}